const fortunesTR = [
    "Güzel şeyler geliyor. Hazır ol. 🌟",
    "Gizli bir fırsat ortaya çıkacak. Açık ol. 🔍",
    "Her şey yerli yerine oturuyor. Zamanlamaya güven. ⏳",
    "Eski bir arkadaşın paylaşacak bir şeyi var. Dikkatle dinle. 👂",
    "Yeni bir yolculuk seni bekliyor. Öğrenmeye hazır ol. 🚀",
    "Güçlüsün. İlerlemeye devam et. 💪",
    "Para yolda. Akıllıca kullan. 💰",
    "Aşk seni şaşırtacak. Sabırlı ol. ❤️",
    "Bir sır açığa çıkacak. Gerçek seni özgür kılacak. 🔑",
    "Yaratıcılığın artacak. Parlamasına izin ver. 🎨",
    "İçgüdülerine güven. Sana yol gösterecek. 🧭",
    "Bir buluşma hayatını değiştirecek. Açık ol. 🤝",
    "Cevaplar içinde. Düşünmek için zaman ayır. 🤔",
    "Yeni bir dostluk neşe getirecek. Anın tadını çıkar. 😊",
    "Rüyaların anlam taşıyor. Dikkat et. 🌙",
    "Yakında iyi haberler geliyor. Umutlu ol. 📩",
    "Hayat lehine değişiyor. Değişimi karşıla. 🔄",
    "Sürpriz bir hediye mutluluk getirecek. Minnettar ol. 🎁",
    "Bildiğinden daha güçlüsün. Zorluğun üstesinden gel. 🏋️",
    "Büyük bir farkındalık yaklaşıyor. Açık fikirli ol. 💡",
    "Geçmişte bilgelik var. Ondan öğren. 📜",
    "Korunuyorsun. Güvende hisset. 🕊️",
    "Huzur yakın. Kalbini ve aklını dengele. ☯️",
    "Büyüme şansı geliyor. Kabul et. 🌱",
    "Şanslı bir şey olacak. Hazır ol. 🍀",
    "Çaban karşılığını bulacak. Devam et. 🏆",
    "Gizli bir yetenek ortaya çıkacak. İyi kullan. 🎭",
    "Mutluluk vazgeçmekten gelir. Affet ve ilerle. 💞",
    "Yeni bir başlangıç seni bekliyor. Macerayı kucakla. 🌅",
    "Öteden bir işaret geliyor. Dikkat et. 🔮",
    "Yeni bir bölüm başlıyor. Hoş geldin de. 📖",
    "Nazik bir davranış gününü güzelleştirecek. Devam ettir. ❤️",
    "Başarı yakın. Odaklan. 🎯",
    "Cesaret ödüller getirecek. Risk al. 🦁",
    "Birisi sana tavsiyede bulunacak. Dikkatle dinle. 👂",
    "Yeni bir düşünce tarzı cevaplar getirecek. 🧠",
    "Sandığından daha dayanıklısın. Kendine inan. 💪",
    "Neşeli bir an hayatın güzelliğini hatırlatacak. 🌻",
    "Cevap sandığından daha yakın. Tekrar bak. 👀",
    "Bir macera seni bekliyor. İleri adım at. 🌍",
    "Yeni arkadaşlar yeni fırsatlar getirecek. Açık ol. 🤗",
    "Verdiğin sana geri dönecek. Pozitif kal. 🔄",
    "İçgüdülerin doğru. Onları takip et. 🧭",
    "Büyük bir atılım geliyor. İtmeye devam et. 🚀",
    "Bilmediğin bir güç bulacaksın. 💪",
    "Mutluluk içinden başlar. Kendini sev. 💖",
    "Bir fikir harika bir şeye yol açacak. Harekete geç. 💡",
    "Çabaların fark ediliyor. Takdir geliyor. 👏",
    "Dürüst bir konuşma seni birine yaklaştıracak. 💬",
    "Her zorluk bir adım ileri. Devam et. ⛰️",
    "İyiliğin birine yardım edecek. 🤝",
    "İyi değişimler oluyor. Akışa bırak. 🌊",
    "Çaban büyümeye başlıyor. Sabırlı ol. 🌿",
    "Bir meydan okuma seni sınayacak. Güçlü dur. 💪",
    "Bir iltifat gününü güzelleştirecek. Kabul et. 😊",
    "Geleceğini sen yaratırsın. Akıllıca seç. 🏗️",
    "İşaretler her yerde. Dikkat et. 👁️",
    "Risk almak harika bir şeye yol açacak. 🎲",
    "Etrafında sevgi var. Fark et. 💕",
    "Geçmişten bir şey mutluluk getirecek. 🎞️",
    "İyileşiyorsun. Devam et. 🏥",
    "Netlik sessiz anlarda gelecek. Düşünmek için zaman ayır. 🧘",
    "Yakında mutlu bir sürpriz var. Keyfini çıkar. 🎉",
    "İyiliğin başkalarına ilham verecek. 🌈",
    "Kalbin güçlü. Bunu yapabilirsin. ❤️",
    "Sabır büyük ödüller getirecek. 🕰️",
    "Bir öğrenme şansı geliyor. Meraklı ol. 📚",
    "Yeniden başlamak yeni kapılar açacak. 🚪",
    "Unuttuğun bir rüya geri dönecek. Peşinden git. 🌠",
    "Huzur içinden gelir. Dengenı bul. 🕊️",
    "Yolun eşsiz. Gururla yürü. 🚶",
    "Sessizlik içgörü getirecek. Yansıtmak için bir an ayır. 🤫",
    "Basit bir nezaket yeni dostluklar getirecek. 🤗",
    "Sandığından daha yetkinsin. Kendine inan. ⭐",
    "Yeni bir hobi neşe getirecek. Yeni bir şey dene. 🎸",
    "Geçmişte dersler var. Onlardan öğren. 📖",
    "Hayat kendi tarzında güzel. Tadını çıkar. 🌺",
    "Hedeflerin sandığından daha yakın. Devam et. 🎯",
    "Samimi bir özür bir bağı onaracak. 💌",
    "Her fırtınayı atlatabilirsin. Güçlü dur. ⛈️",
    "Bolluk sana doğru geliyor. Buna açık ol. 💰",
    "İyiliğin mutluluk yayacak. 💞",
    "Önündeki yol zor ama buna değer. 🛤️",
    "Bir rehber sana yol gösterecek. Öğrenmeye açık ol. 👩‍🏫",
    "Yolun sevgi ve ışıkla dolu. 🌟",
    "Cevaplar beklenmedik yollarla gelecek. 🌀",
    "Bir netlik anı geleceğini değiştirecek. 🔥",
    "Gizli bir nimet geliyor. Buna açık ol. 🎁",
    "Bırakmak huzur getirecek. 🌿",
    "Sen başkalarına ışık oluyorsun. Parlamaya devam et. ✨",
    "Zor bir seçim büyümeye yol açacak. 🌳",
    "Küçük bir zafer daha büyük şeylere yol açacak. 🏅",
    "Verdiğin sana geri dönecek. 🔄",
    "Değişim burada. Hoş geldin de. 🌈",
    "Bir mesaj beklenmedik mutluluk getirecek. 💌",
    "Yolculuğun mükemmel bir şekilde açılıyor. 🛤️",
    "Minnettarlık bakış açını değiştirecek. 🙏",
    "Hayatını değiştirecek biriyle tanışacaksın. 🤝",
    "Yaratıcılık yeni olasılıklar açacak. 🎨",
    "Cesaretin başkalarına ilham veriyor. 🦸",
    "Sabır en iyi ödülleri getirecek. 🕰️",
    "Eski bir anı sana yeni bir şey öğretecek. 🏞️",
    "Adapte ol ve büyü. Güçlüsün. 🌱",
    "Şanslı bir an gününü aydınlatacak. 🍀",
    "Neşen bulaşıcı. Paylaş. 😄",
    "Büyük bir değişim geliyor. Hazır ol. 🔄",
    "Aşk sandığından daha yakın. 💗",
    "Beklenmedik biri sana yardım edecek. 👏",
    "Huzur kalbinle başlar. Bul onu. ☮️",
    "Kararlılık başarıya götürecek. 🚀",
    "Beklenmedik bir dönüş daha iyiye yol açacak. 🔀",
    "Tam olman gereken yerdesin. 🏡",
    "Geçmişte dersler var. Kullan onları. 📜",
    "Büyük bir an geliyor. Hazır ol. 🎇",
    "Rüyaların geleceğine rehberlik ediyor. Takip et onları. 🌠",
    "İlham verici bir mesaj sana doğru geliyor. 💌",
    "Yeni bir başlangıç yeni umut getirecek. 🌿",
    "İyiliğin fark yaratacak. ❤️",
    "Affetmek seni özgür bırakacak. 🔓",
    "İlham verici bir an değişimi tetikleyecek. 💡",
    "Hikayen hâlâ yazılıyor. Harika yap onu. ✍️"
  ];

  const fortunesEN = [
    "Good things are coming. Be ready. 🌟",
    "A hidden chance will show up. Stay open. 🔍",
    "Everything is falling into place. Trust the timing. ⏳",
    "An old friend has something to share. Listen closely. 👂",
    "A new journey is ahead. Be ready to learn. 🚀",
    "You are strong. Keep moving forward. 💪",
    "Money is on the way. Use it wisely. 💰",
    "Love will surprise you. Be patient. ❤️",
    "A secret will come out. The truth will free you. 🔑",
    "Your creativity will grow. Let it shine. 🎨",
    "Trust your gut. It will show you the way. 🧭",
    "A meeting will change your life. Stay open. 🤝",
    "The answers are inside you. Take time to think. 🤔",
    "A new friendship will bring joy. Enjoy the moment. 😊",
    "Your dreams have meaning. Pay attention. 🌙",
    "Good news is coming soon. Stay hopeful. 📩",
    "Life is shifting in your favor. Welcome the change. 🔄",
    "A surprise gift will bring happiness. Be thankful. 🎁",
    "You are stronger than you know. Face the challenge. 🏋️",
    "A big realization is coming. Be open-minded. 💡",
    "The past has wisdom for you. Learn from it. 📜",
    "You are being protected. Feel safe. 🕊️",
    "Peace is near. Balance your heart and mind. ☯️",
    "A chance to grow is coming. Take it. 🌱",
    "Something lucky is about to happen. Be ready. 🍀",
    "Your hard work will pay off. Keep going. 🏆",
    "A hidden talent will show itself. Use it well. 🎭",
    "Happiness comes from letting go. Forgive and move on. 💞",
    "A new start is ahead. Embrace the adventure. 🌅",
    "A sign from beyond is coming. Pay attention. 🔮",
    "A fresh chapter is beginning. Welcome it. 📖",
    "A kind act will make your day. Pass it on. ❤️",
    "Success is close. Stay focused. 🎯",
    "Bravery will bring rewards. Take the risk. 🦁",
    "Someone has advice for you. Listen carefully. 👂",
    "A new way of thinking will bring answers. 🧠",
    "You are tougher than you think. Believe in yourself. 💪",
    "A joyful moment will remind you of life’s beauty. 🌻",
    "The answer is closer than you think. Look again. 👀",
    "An adventure is waiting. Step forward. 🌍",
    "New friends will bring new chances. Be open. 🤗",
    "What you give will come back to you. Stay positive. 🔄",
    "Your instincts are right. Follow them. 🧭",
    "A big breakthrough is coming. Keep pushing. 🚀",
    "You will find strength you didn’t know you had. 💪",
    "Happiness starts inside you. Love yourself. 💖",
    "An idea will spark something amazing. Take action. 💡",
    "People are noticing your efforts. Recognition is coming. 👏",
    "An honest talk will bring you closer to someone. 💬",
    "Every challenge is a step forward. Keep going. ⛰️",
    "Your kindness will help someone in need. 🤝",
    "Good changes are happening. Go with the flow. 🌊",
    "Your hard work is starting to grow. Be patient. 🌿",
    "A challenge will test you. Stay strong. 💪",
    "A compliment will make your day. Accept it. 😊",
    "You create your future. Choose wisely. 🏗️",
    "Signs are everywhere. Pay attention. 👁️",
    "Taking a chance will lead to something amazing. 🎲",
    "Love is all around you. Notice it. 💕",
    "Something from the past will bring happiness. 🎞️",
    "You are healing. Keep going. 🏥",
    "Clarity will come in quiet moments. Take time to think. 🧘",
    "A happy surprise is near. Enjoy it. 🎉",
    "Your kindness will inspire others. 🌈",
    "Your heart is strong. You can do this. ❤️",
    "Patience will bring great rewards. 🕰️",
    "A learning chance is coming. Be curious. 📚",
    "Starting fresh will open new doors. 🚪",
    "A dream you forgot will return. Chase it. 🌠",
    "Peace comes from within. Find your balance. 🕊️",
    "Your path is unique. Walk it proudly. 🚶",
    "Silence will bring insight. Take a moment to reflect. 🤫",
    "A simple kindness will bring new friendships. 🤗",
    "You are more capable than you think. Believe in yourself. ⭐",
    "A new hobby will bring joy. Try something new. 🎸",
    "The past has lessons for you. Learn from them. 📖",
    "Life is beautiful in its own way. Enjoy it. 🌺",
    "Your goals are closer than you think. Keep going. 🎯",
    "A sincere apology will mend a bond. 💌",
    "You can weather any storm. Stay strong. ⛈️",
    "Abundance is coming your way. Be open to it. 💰",
    "Your kindness will spread happiness. 💞",
    "The road ahead is tough, but worth it. 🛤️",
    "A mentor will guide you. Be open to learning. 👩‍🏫",
    "Your path is filled with love and light. 🌟",
    "The answers will come in unexpected ways. 🌀",
    "A moment of clarity will change your future. 🔥",
    "A hidden blessing is coming. Stay open to it. 🎁",
    "Letting go will bring peace. 🌿",
    "You are a light to others. Keep shining. ✨",
    "A hard choice will bring growth. 🌳",
    "A small win will lead to bigger things. 🏅",
    "What you give will come back to you. 🔄",
    "Change is here. Welcome it. 🌈",
    "A message will bring unexpected happiness. 💌",
    "Your journey is unfolding perfectly. 🛤️",
    "Gratitude will change your outlook. 🙏",
    "You will meet someone who will change your life. 🤝",
    "Creativity will unlock new possibilities. 🎨",
    "Your courage inspires others. 🦸",
    "Patience will bring the best rewards. 🕰️",
    "An old memory will teach you something new. 🏞️",
    "Adapt and grow. You are strong. 🌱",
    "A lucky moment will brighten your day. 🍀",
    "Your joy is contagious. Share it. 😄",
    "A big change is coming. Be ready. 🔄",
    "Love is closer than you think. 💗",
    "Someone unexpected will help you. 👏",
    "Peace starts in your heart. Find it. ☮️",
    "Determination will lead to success. 🚀",
    "An unexpected turn will lead to something better. 🔀",
    "You are right where you need to be. 🏡",
    "The past holds lessons. Use them. 📜",
    "A big moment is coming. Be ready. 🎇",
    "Your dreams guide your future. Follow them. 🌠",
    "An uplifting message is coming your way. 💌",
    "A fresh start will bring new hope. 🌿",
    "Your kindness will make a difference. ❤️",
    "Forgiveness will set you free. 🔓",
    "An inspired moment will spark change. 💡",
    "Your story is still being written. Make it great. ✍️"
  ];

  export { fortunesTR, fortunesEN };
