const words = {
    tr: [
        "ANNE", "BABA", "KARDEŞ", "EV", "ARABA", "SU", "YEMEK", "İÇMEK", "GİTMEK", "GELMEK",
        "OKUL", "KİTAP", "KALEM", "DEFTER", "ÖĞRETMEN", "ARKADAŞ", "İŞ", "PARA", "ZAMAN", "GÜN",
        "GECE", "SABAH", "AKŞAM", "HAVA", "GÜNEŞ", "AY", "YILDIZ", "DENİZ", "DAĞ", "ORMAN",
        "ÇİÇEK", "AĞAÇ", "KUŞ", "KEDİ", "KÖPEK", "EL", "AYAK", "BAŞ", "GÖZ", "KULAK",
        "SEVGİ", "MUTLU", "ÜZGÜN", "İYİ", "KÖTÜ", "BÜYÜK", "KÜÇÜK", "UZUN", "KISA", "HIZLI",
        "YAVAŞ", "GÜZEL", "ÇİRKİN", "SICAK", "SOĞUK", "YAĞMUR", "KAR", "RÜZGAR", "BULUT", "SİS",
        "YOL", "KAPI", "PENCERE", "ODA", "MASA", "SANDALYE", "YATAK", "DOLAP", "AYNA", "SAAT",
        "TELEFON", "BİLGİSAYAR", "TELEVİZYON", "RADYO", "MÜZİK", "FİLM", "OYUN", "SPOR", "FUTBOL", "BASKETBOL",
        "KOŞMAK", "YÜZMEK", "ATLAMAK", "DANS", "ŞARKI", "SES", "GÜRÜLTÜ", "SAKİN", "KALABALIK", "BOŞ",
        "DOLU", "TEMİZ", "KİRLİ", "YENİ", "ESKİ", "RENK", "KIRMIZI", "MAVİ", "YEŞİL", "SARI",
        "SİYAH", "BEYAZ", "GRİ", "MOR", "TURUNCU", "PEMBE", "KAHVERENGİ", "ALTIN", "GÜMÜŞ", "TAŞ",
        "TOPRAK", "KUM", "ÇAKIL", "ÇİMEN", "BAHÇE", "PARK", "SOKAK", "CADDE", "KÖPRÜ", "NEHİR",
        "GÖL", "DALGA", "BALIK", "YENGEÇ", "KAPLUMBAĞA", "TAVUK", "HOROZ", "İNEK", "KOYUN", "KEÇİ",
        "AT", "EŞEK", "FARE", "YILAN", "ÖRÜMCEK", "BÖCEK", "ARI", "KELEBEK", "SİNEK", "KURBAĞA",
        "ET", "TAVUK", "BALIK", "EKMEK", "PEYNİR", "ZEYTİN", "YUMURTA", "SÜT", "YOĞURT", "TEREYAĞI",
        "ÇAY", "KAHVE", "SU", "MEYVE", "ELMA", "ARMUT", "ÜZÜM", "PORTAKAL", "MANDALİNA", "MUZ",
        "ÇİLEK", "KİRAZ", "KARPUZ", "KAVUN", "ŞEFTALİ", "KAYISI", "ERİK", "NAR", "İNCİR", "HURMA",
        "SEBZE", "DOMATES", "SALATALIK", "BİBER", "PATATES", "SOĞAN", "SARIMSAK", "HAVUÇ", "LAHANA", "MARUL",
        "ISPANAK", "FASULYE", "NOHUT", "MERCİMEK", "PİRİNÇ", "MAKARNA", "ÇORBA", "SALATA", "TATLI", "KEK",
        "KURABİYE", "DONDURMA", "ÇİKOLATA", "ŞEKER", "TUZ", "BİBER", "YAĞ", "UN", "SU", "İÇECEK",
        "BARDAK", "TABAK", "KAŞIK", "ÇATAL", "BIÇAK", "KASE", "TENCERE", "TAVA", "FIRIN", "BUZDOLABI",
        "ÇAMAŞIR", "SABUN", "ŞAMPUAN", "DİŞ", "MACUN", "FIRÇA", "HAVLU", "TARAK", "AYAKKABI", "ÇORAP",
        "PANTOLON", "GÖMLEK", "KAZAK", "CEKET", "MONT", "ŞAPKA", "BERE", "ELDİVEN", "KEMER", "ÇANTA",
        "CÜZDAN", "ANAHTAR", "KİLİT", "KAPI", "DUVAR", "ÇATI", "ZEMİN", "MERDİVEN", "ASANSÖR", "BALKON",
        "PERDE", "HALI", "KOLTUK", "KANEPE", "YASTIK", "BATTANİYE", "ÇARŞAF", "UYKU", "RÜYA", "UYANMAK",
        "ÇALIŞMAK", "DİNLENMEK", "OKUMAK", "YAZMAK", "ÇİZMEK", "BOYAMAK", "KONUŞMAK", "DİNLEMEK", "ANLAMAK", "SORMAK",
        "CEVAP", "SORU", "DOĞRU", "YANLIŞ", "BELKİ", "TABİİ", "ELBETTE", "ASLA", "HİÇ", "HER",
        "BAZI", "BİRAZ", "ÇOK", "AZ", "TAMAM", "EVET", "HAYIR", "LÜTFEN", "TEŞEKKÜR", "RİCA",
        "AFEDERSİNİZ", "PARDON", "MERHABA", "SELAM", "HOŞÇAKAL", "GÜLE", "İYİ", "KÖTÜ", "HASTA", "SAĞLIK",
        "DOKTOR", "HASTANE", "İLAÇ", "ATEŞ", "SOĞUK", "SICAK", "AĞRI", "YARA", "KAN", "BAŞ",
        "KALP", "AKCİĞER", "MİDE", "KOL", "BACAK", "PARMAK", "TIRNAK", "SAÇ", "SAKAL", "BIYIK",
        "GÖZLÜK", "KULAKLIK", "ŞEMSİYE", "YAĞMURLUK", "GÜNEŞ", "GÖLGE", "SICAKLIK", "DERECE", "HAVA", "MEVSİM",
        "İLKBAHAR", "YAZ", "SONBAHAR", "KIŞ", "AY", "HAFTA", "YIL", "DÜN", "BUGÜN", "YARIN",
        "ŞİMDİ", "SONRA", "ÖNCE", "ERKEN", "GEÇ", "DAKİKA", "SAAT", "GÜN", "AY", "YIL",
        "DOĞUM", "ÖLÜM", "YAŞ", "GENÇ", "YAŞLI", "BEBEK", "ÇOCUK", "YETİŞKİN", "AİLE", "TEYZE",
        "AMCA", "DAYI", "HALA", "DEDE", "NİNE", "TORUN", "EŞ", "KOCA", "KARI", "NİŞANLI",
        "DÜĞÜN", "EVLİLİK", "BOŞANMA", "AŞK", "NEFRET", "KORKU", "UMUT", "HAYAL", "GERÇEK", "YALAN",
        "SIR", "HEDİYE", "SÜRPRİZ", "TEBRİK", "KUTLAMA", "BAYRAM", "YILBAŞI", "TATİL", "GEZİ", "SEYAHAT",
        "UÇAK", "TREN", "OTOBÜS", "TAKSİ", "BİSİKLET", "YÜRÜMEK", "DURMAK", "BEKLEMEK", "BAŞLAMAK", "BİTMEK",
        "DEĞİŞMEK", "KALMAK", "AYRILMAK", "BULUŞMAK", "TANIŞMAK", "YARDIM", "DESTEK", "PAYLAŞMAK", "ALMAK", "VERMEK",
        "SATMAK", "SATIN", "FİYAT", "UCUZ", "PAHALI", "MAĞAZA", "MARKET", "PAZAR", "DÜKKAN", "KASİYER",
        "MÜŞTERİ", "KALİTE", "MİKTAR", "AĞIRLIK", "BOYUT", "ŞEKİL", "YUVARLAK", "KARE", "ÜÇGEN", "DÜZ",
        "EĞRİ", "DAR", "GENİŞ", "DERİN", "SIĞ", "YÜKSEK", "ALÇAK", "YAKIN", "UZAK", "SAĞ",
        "SOL", "ÖN", "ARKA", "YAN", "İÇ", "DIŞ", "ÜST", "ALT", "ORTA", "KENAR",
        "YER", "MEKAN", "ADRES", "HARİTA", "YOL", "TRAFİK", "ARABA", "KAMYON", "MOTOSİKLET", "SİNYAL",
        "LAMBA", "IŞIK", "KARANLIK", "GÖLGE", "AYNA", "CAM", "METAL", "PLASTİK", "KAĞIT", "KARTON",
        "TAHTA", "BETON", "TUĞLA", "BOYA", "FIRÇA", "ÇEKİÇ", "ÇİVİ", "VİDA", "ALET", "MAKİNE",
        "ELEKTRİK", "PİL", "KABLO", "PRİZ", "DÜĞME", "AÇMAK", "KAPAMAK", "KIRMAK", "TAMİR", "YAPMAK",
        "BOZMAK", "KESMEK", "YAPIŞTIRMAK", "BAĞLAMAK", "ÇÖZMEK", "DİKİŞ", "İĞNE", "İPLİK", "KUMAŞ", "DERİ",
        "YÜN", "PAMUK", "İPEK", "DÜĞME", "FERMUAR", "DESEN", "ÇİZGİ", "NOKTA", "DAİRE", "KÜP",
        "SİLİNDİR", "TOP", "KUTU", "PAKET", "ÇANTA", "VALİZ", "AĞIRLIK", "ÖLÇMEK", "METRE", "KİLOMETRE",
        "GRAM", "KİLOGRAM", "LİTRE", "SIVI", "KATI", "GAZ", "BUHAR", "DUMAN", "ATEŞ", "YANMAK",
        "SÖNMEK", "ISI", "ENERJİ", "GÜÇ", "HIZ", "YAVAŞ", "DENGE", "DÜŞMEK", "KALKMAK", "TAŞIMAK"
    ],
    en: [
        "TREE", "FAMILY", "MIND", "GOLD", "PEAR", "LION", "MIRROR", "FISH", "BALCONY", "BABY",
        "PEPPER", "WISE", "BUILDING", "CLOUD", "GLASS", "POCKET", "FLOWER", "CHILD", "NOTEBOOK", "WARDROBE",
        "WORLD", "APPLE", "EFFORT", "MOUSE", "ELEPHANT", "NEWSPAPER", "SUN", "CARROT", "IMAGINATION", "INDIA",
        "SPAIN", "ISTANBUL", "HUMAN", "WOMAN", "PEN", "TURTLE", "ANT", "MELON", "CAT",
        "BOOK", "DOG", "BIRD", "CABBAGE", "LEMON", "SCISSORS", "TABLE", "BANANA", "BUS", "DUCK",
        "PARROT", "POTATO", "EGGPLANT", "WINDOW", "ORANGE", "CUCUMBER", "CHAIR", "SQUIRREL",
        "ONION", "MILK", "HAT", "CITY", "PLATE", "RABBIT", "PHONE", "TURKEY", "AIRPLANE", "GRAPE",
        "CHERRY", "LEAF", "BED", "SNAKE", "YOGURT", "ZEBRA", "OLIVE", "GIRAFFE", "GERMANY",
        "CAR", "BEAR", "BALLOON", "BANK", "BICYCLE", "BULGARIA", "WALNUT", "PINETREE", "STRAWBERRY",
        "SEA", "ICECREAM", "BUTTON", "BREAD", "ELECTRICITY", "BEANS", "FRANCE", "FUTURE", "GLASSES",
        "GRAPEFRUIT", "CARPET", "HAMBURGER", "SPINACH", "ENGLAND", "ITALY", "JAPAN", "CANADA",
        "CAN", "DOOR", "WATERMELON", "EAGLE", "APRICOT", "BOOKSHELF", "BRIDGE", "VILLAGE", "COOKIE",
        "NORTH", "STORK", "PORT", "MANDARIN", "MEXICO", "LENTIL", "OAK", "FRUIT", "CORN", "CHAT",
        "POMEGRANATE", "ARMY", "FOREST", "SPIDER", "PALM", "PANTS", "DAISY", "MONEY", "CHICKEN",
        "RICE", "BEACH", "POLAND", "RADIO", "COLORFUL", "ROME", "DREAM", "CLOCK", "GARLIC",
        "POT", "VEGETABLE", "SILLY", "CINEMA", "COLD", "STREET", "VACUUM", "UMBRELLA", "FIELD",
        "TELEVISION", "SLIPPERS", "CROCODILE", "SEED", "TOMATO", "TRACTOR", "TRAIN", "TOURIST",
        "PICKLE", "KITE", "UNIVERSITY", "FERRY", "FAN", "FOOD", "CRAB", "STAR", "ROAD", "GREECE",
        "RING", "LILY", "HARM", "OLIVEOIL", "BELL", "ABACUS", "USA", "AFRICA", "MOUNTAIN",
        "MEDITERRANEAN", "SCORPION", "AQUARIUM", "TROUT", "AMERICA", "PINEAPPLE", "MAUSOLEUM",
        "ARGENTINA", "IMPUDENT", "ELEVATOR", "ASIA", "AUSTRALIA", "SUNFLOWER", "HONEY", "CUP",
        "WEST", "FLAG", "BELGIUM", "WHITE", "BILLIARDS", "BISCUIT", "BLOCK", "BUG", "REGION",
        "BIG", "HEAVEN", "FACADE", "REPUBLIC", "TENT", "JACKAL", "WALK", "BAG", "BARRACK",
        "HAMMER", "CIRCASSIAN", "CHOCOLATE", "CEMENT", "CHINA", "NAIL", "TRASH", "LACE", "LAUREL",
        "YOUTHFUL", "BALANCE", "STREAM", "CAMEL", "SEWING", "LANGUAGE", "DYNAMO", "TOOTH", "KNEE",
        "DOCTOR", "HAIL", "FRIEND", "LIP", "WEDDING", "SOUR", "GLOVES", "ENERGY", "PLUM",
        "OLD", "JOKE", "TAG", "SEPTEMBER", "MOROCCO", "LANTERN", "FESTIVAL", "IDEA", "DRESS",
        "RECEIPT", "SEAL", "PHOTO", "BRAKE", "FOOTBALL", "BREAK", "WIN", "GARAGE", "PLANET",
        "ENTRY", "SKY", "LAKE", "SHIRT", "FERTILIZER", "ROSE", "SILVER", "SOUTH", "NOISE",
        "NEWS", "PEOPLE", "ANCHOVY", "MAP", "HARVEST", "AVIATION", "TOWEL", "GHOST", "HELICOPTER",
        "ROOSTER", "GOVERNMENT", "LIME", "WARM", "RIVER", "WET", "NEEDLE", "CLIMATE", "COW",
        "CONSTRUCTION", "STRING", "SKELETON", "STATION", "CLAM", "GENDARME", "CANDY", "JET",
        "RAZOR", "JUPITER", "PUMPKIN", "CABIN", "CAGE", "COFFEE", "CACTUS", "SIDEWALK", "PENCIL",
        "CASE", "HEART", "CAMERA", "CANARY", "COUCH", "COVER", "SNOW", "BLACK", "CROW", "CARD",
        "BUTCHER", "SPOON", "POPULUS", "ROCK", "SKATEBOARD", "GOAT", "BELT", "SHOVEL", "CHESTNUT",
        "DISCOVERY", "RUG", "PERSON", "KOALA", "ARMCHAIR", "NEIGHBOR", "CONFERENCE", "CONTROL",
        "COPY", "PROTECTION", "SHEEP", "COCOON", "COAL", "SAND", "PIGGYBANK", "SHOE", "FROG",
        "DRY", "SNACK", "BOX", "SMALL", "MOLD", "CULTURE", "LAVENDER", "HIGH", "SCHOOL",
        "LUXURY", "MEDAL", "SUBSTANCE", "CAVE", "PASTA", "MATERIAL", "DAIRY", "MAGNOLIA", "MUSHROOM",
        "LETTUCE", "FAIRYTALE", "BLUE", "MAY", "FLOOD", "COUNCIL", "BREEZE", "STAIRCASE", "CENTER",
        "SEASON", "MICROPHONE", "GUEST", "MEETING", "TEMPERAMENT", "ENGINE", "ACCOUNTING", "CANDLE",
        "KITCHEN", "MUSEUM", "CASH", "MINT", "APRIL", "NORMAL", "GRADE", "POPULATION", "JANUARY",
        "ROOM", "WOOD", "SCHOOL", "FISHINGROD", "OMEGA", "ORGAN", "MIDDLE", "HERB", "HOTEL",
        "HIGHWAY", "GRIND", "PRIZE", "NOON", "TEACHER", "MEASURE", "KNIT", "EXAMPLE", "CLOTH",
        "SPECIAL", "FREEDOM", "COAT", "COTTON", "PANDA", "PARAGRAPH", "PARACHUTE", "FINGER",
        "SHARE", "CURTAIN", "THURSDAY", "HONEYCOMB", "CHEESE", "PITA", "BATTERY", "PIANO", "PIZZA",
        "RECORD", "POLICE", "PORTUGAL", "OFFICE", "PRACTICAL", "STAMP", "COMPASS", "SHELF",
        "COMFORT", "COLOR", "PICTURE", "RACK", "RIZE", "ROCKET", "WIND", "SOAP", "HEALTH",
        "GUM", "SALAD", "HALL", "BOAT", "YELLOW", "PAGE", "JOURNEY", "COFFEETABLE", "EIGHT",
        "GREETINGS", "YOU", "GREENHOUSE", "QUIET", "LEVEL", "HOT", "CATTLE", "WIPE", "SYMBOLS",
        "FLY", "NERVE", "TRENCH", "VINEGAR", "MIST", "SITE", "SODA", "BREATH", "LAST",
        "AUTUMN", "QUESTION", "SOCIAL", "LINEAGE", "WORD", "SPORT", "WATER", "IRRIGATION", "PRESENTATION",
        "JUG", "TIME", "EXILE", "DAWN", "HAWK", "SCARF", "SHAMPOO", "SONG", "STRAP",
        "POEM", "BOTTLE", "TEAM", "DEMAND", "FULL", "GRAINY", "TANK", "COMB", "HISTORY",
        "DESIGN", "CEILING", "ADVICE", "TYFOON", "WHEEL", "TELEPHONE", "COPYRIGHT", "CLEAN",
        "DELIVERY", "THANK", "SICKLE", "TRADE", "THEATER", "SLAP", "BALL", "TOP", "SOIL",
        "TRAFFIC", "TOURISM", "GLUE", "SALT", "RIFLE", "ALL", "TUBE", "CHEAP", "PLANE",
        "SLEEP", "FEE", "COUNTRY", "UNIT", "PRODUCTION", "UPPER", "VASE", "PARENT", "TAX",
        "VIDEO", "TURN", "VOLCANO", "EMPHASIS", "RAIN", "RUBY", "LIE", "SLOPE", "FIRE",
        "BAT", "PILLOW", "LIFE", "WRITER", "ANEMOMETER", "MEAL", "GROUND", "GREEN", "YEAR",
        "COMMENT", "EGG", "GREEK", "LOAD", "FACE", "AGRICULTURE", "DIFFICULT", "GROUP"
    ],
    de: [
        "BAUM", "FAMILIE", "VERSTAND", "GOLD", "BIRNE", "LÖWE", "SPIEGEL", "FISCH", "BALKON", "BABY",
        "PFEFFER", "WEISE", "GEBÄUDE", "WOLKE", "GLAS", "TASCHE", "BLUME", "KIND", "NOTIZBUCH", "KLEIDERSCHRANK",
        "WELT", "APFEL", "MÜHE", "MAUS", "ELEFANT", "ZEITUNG", "SONNE", "MÖHRE", "VORSTELLUNG",
        "SPANIEN", "ISTANBUL", "MENSCH", "FRAU", "KUGELSCHREIBER", "SCHILDKRÖTE", "AMEISE", "MELONE", "KATZE",
        "BUCH", "HUND", "VOGEL", "KOHL", "ZITRONE", "SCHERE", "TISCH", "BANANE", "BUS", "ENTE",
        "PAPAGEI", "KARTOFFEL", "AUBERGINE", "FENSTER", "ORANGE", "GURKE", "STUHL", "EICHHÖRNCHEN",
        "ZWIEBEL", "MILCH", "HUT", "STADT", "TELLER", "KANINCHEN", "TELEFON", "TÜRKEI", "FLUGZEUG", "TRAUBE",
        "KIRSCHE", "BLATT", "BETT", "SCHLANGE", "JOGHURT", "ZEBRA", "OLIVE", "GIRAFFE", "DEUTSCHLAND",
        "AUTO", "BÄR", "LUFTBALLON", "BANK", "WALNUSS", "KIEFER", "HEUSCHRECKE", "ERDBEERE", "MEER",
        "EIS", "KNOPF", "BROT", "STROM", "BOHNE", "FRANKREICH", "ZUKUNFT", "BRILLE", "GRAPEFRUIT",
        "TEPPICH", "HAMBURGER", "PUTENFLEISCH", "SPINAT", "ENGLAND", "ITALIEN", "JAPAN", "KANADA",
        "WASSERMELONE", "ADLER", "APRIKOSE", "BUCHREGAL", "BRÜCKE", "DORF", "KUCHEN", "NORDEN",
        "STORCH", "HAFEN", "MANDARINE", "GRILL", "MEXIKO", "LINSE", "EICHE", "FRUCHT", "MAIS",
        "GESPRÄCH", "GRANATAPFEL", "ARMEE", "WALD", "SPINNE", "PALME", "HOSE", "GÄNSEBLUME",
        "GELD", "HÜHNCHEN", "REIS", "STRAND", "POLEN", "RADIO", "BUNT", "ROM", "TRAUM",
        "UHR", "KNOBLAUCH", "TOPF", "GEMÜSE", "DOOF", "KINO", "KALT", "STAUBSAUGER", "FELD",
        "FERNSEHEN", "SCHUH", "KROKODIL", "SAMEN", "TOMATE", "TRAKTOR", "ZUG", "TOURIST",
        "SAUERKRAUT", "DRACHE", "UNIVERSITÄT", "FÄHRE", "WIEN", "FÄCHER", "ESSEN", "KREBS",
        "STERN", "WEG", "GRIECHENLAND", "RING", "LILIE", "SCHADEN", "OLIVENÖL", "GLOCKE",
        "ABAKUS", "SCHMERZ", "MITTELMEER", "SKORPION", "AQUARIUM", "FORELLE", "ANANAS", "ARABER",
        "ARGENTINIEN", "FRECH", "AUFZUG", "ASIEN", "AUSTRALIEN", "SONNENBLUME", "HONIG", "OKRA",
        "WESTEN", "FLAGGE", "BELGIEN", "BILLARD", "KEKS", "BLOCK", "INSEKT", "REGION",
        "PARADIES", "FRONT", "REPUBLIK", "ZELT", "SCHAKAL", "BUSCH", "MARKT", "HAMMER",
        "TSCHERKESSE", "SCHOKOLADE", "ZEMENT", "CHINA", "NAGEL", "MÜLL", "SPITZE", "LORBEER",
        "JUNGMANN", "GLEICHGEWICHT", "BACH", "KAMEL", "NÄHEN", "ZUNGE", "DYNAMO", "ZAHN", "KNIE",
        "ARZT", "VOLL", "FREUND", "LIPPE", "HOCHZEIT", "SAUER", "HANDSCHUH", "ENERGIE",
        "PFLAUME", "WITZ", "ETIKETT", "SEPTEMBER", "MAROKKO", "LATERNE", "FESTIVAL", "SETZLING",
        "IDEE", "KLEID", "BON", "ROBBE", "FOTO", "BREMSE", "WAHRSCHEINLICH", "GARAGE",
        "PLANET", "EINGANG", "HIMMEL", "SEE", "HEMD", "DÜNGER", "ROSE", "SILBER",
        "SÜDEN", "LÄRM", "NACHRICHT", "VOLK", "SARDINE", "ERNDTE", "LUFTFAHRT", "HANDTUCH",
        "GEIST", "HELIKOPTER", "TRUTHUHN", "INDIEN", "HAHN", "REGIERUNG", "LINDENBLÜTE", "LAUWARM",
        "FLUSS", "NASS", "NADEL", "KLIMA", "KUH", "BAU", "SEIL", "SKELETT",
        "BAHNHOF", "AUSTER", "GENDARM", "JAPANER", "GUMMIBÄRCHEN", "JET", "RASIERER", "JUPITER",
        "KÜRBIS", "KABINE", "KÄFIG", "KAFFEE", "KAKTUS", "BÜRGERSTEIG", "FEDERMAPPE", "HERZ",
        "KAMERA", "KANARIENVOGEL", "SOFA", "DECKEL", "SCHNEE", "KRÄHE", "KARTE", "METZGER",
        "LÖFFEL", "PAPPEL", "FELS", "SKATEBOARD", "ZIEGE", "GÜRTEL", "SCHIPPE", "KASTANIE",
        "ENTDECKUNG", "ZYPERN", "PERSON", "KOALA", "SESSEL", "NACHBAR", "KONFERENZ", "KONTROLLE",
        "KOPIE", "SCHUTZ", "SCHAF", "KOKON", "SAND", "SPARBÜCHSE", "FROSCH", "TROCKEN",
        "NÜSSE", "BOX", "KLEIN", "SCHIMMEL", "KEGEL", "KULTUR", "RUDER", "LAVENDEL",
        "GYMNASIUM", "LUXUS", "MEDAILLE", "STOFF", "HÖHLE", "TEIGWAREN", "MATERIAL", "MOLKEREI",
        "MAGNOLIE", "PILZ", "KOPFSALAT", "MÄRCHEN", "BLAU", "MAI", "PARLAMENT", "BRISE",
        "TREPPE", "ZENTRUM", "JAHRESZEIT", "OBST", "MIKROFON", "MINARETT", "GAST", "KUNDGEBUNG",
        "GEMÜT", "MOTOR", "BUCHHALTUNG", "KERZE", "KÜCHE", "MUSEUM", "BARGELD", "MINZE",
        "APRIL", "KICHERERBSE", "NORMAL", "NOTE", "BEVÖLKERUNG", "JANUAR", "ZIMMER", "HOLZ",
        "SCHULE", "ANGEL", "OMEGA", "ORGAN", "MITTE", "GRAS", "HOTEL", "AUTOBAHN",
        "REIBEN", "PREIS", "MITTAG", "LEHRER", "STRICK", "BEISPIEL", "DECKE", "SPEZIELL",
        "FREIHEIT", "MANTEL", "BAUMWOLLE", "PANDA", "ABSATZ", "FALLSCHIRM", "FINGER", "HAUSSCHUH",
        "TEILEN", "VORHANG", "DONNERSTAG", "WABE", "KÄSE", "FLADENBROT", "BATTERIE", "KLAVIER",
        "PIZZA", "PLATTE", "POLIZEI", "PORTUGAL", "POSTAMT", "TÜTE", "PRAKTISCH", "BRIEFMARKE",
        "KOMPASS", "REGAL", "BEQUEM", "RAMADAN", "FARBE", "BILD", "ABTEILUNG", "RAKETE",
        "WIND", "SEIFE", "GESUNDHEIT", "KAUGUMMI", "SALAT", "SALON", "BOOT", "SAVANNE",
        "SEITE", "FAHRT", "TISCHCHEN", "ACHT", "DU", "GEWÄCHSHAUS", "LEISE", "NIVEAU",
        "RIND", "RADIEREN", "SYMBOLE", "FLIEGE", "NERV", "SCHUTZWALL", "ESSIG", "NEBEL",
        "SIEDLUNG", "SCHWARZ", "SODA", "ATEM", "ENDE", "HERBST", "FRAGE", "SOZIAL",
        "GESCHLECHT", "WORT", "SPORT", "WASSER", "BEWÄSSERUNG", "PRÄSENTATION", "KARAFFE", "DAUER",
        "EXIL", "MORGENGRAUEN", "FALKE", "SCHAL", "SCHAMPOO", "LIED", "SCHIRM", "STREIFEN",
        "GEDICHT", "FLASCHE", "MANNSCHAFT", "NACFRAGE", "VOLLSTÄNDIG", "KÖRNIG", "PANZER", "KAMM",
        "GESCHICHTE", "DESIGN", "DECKEN", "EMPFEHLUNG", "TAIFUN", "RAD", "URHEBERRECHT", "SAUBER",
        "PANTOFFEL", "LIEFERUNG", "DANKE", "SENSE", "HANDEL", "THEATER", "BALL", "KREISEL",
        "BODEN", "VERKEHR", "TOURISMUS", "EINGELEGTE", "KLEBER", "SALZ", "GEWEHR", "ALLE",
        "RÖHRE", "BILLIG", "SCHLAF", "GEBÜHR", "LAND", "EINHEIT", "PRODUKTION", "OBEN",
        "VASE", "ELTERNTEIL", "STEUER", "VIDEO", "KURVE", "SAUERKIRSCHE", "VULKAN", "BETONUNG",
        "REGEN", "RUBIN", "LÜGE", "HANG", "BRAND", "FLEDERMAUS", "KISSEN", "LEBEN",
        "AUTOR", "ZEIGER", "ORT", "GRÜN", "JAHR", "KOMMENTAR", "EI", "GRIECHISCH",
        "LAST", "GESICHT", "ZEIT", "LANDWIRTSCHAFT", "SCHWIERIG", "GRUPPE"
    ],
    fr: [
        "ARBRE", "FAMILLE", "ESPRIT", "OR", "POIRE", "LION", "MIROIR", "POISSON", "BALCON",
        "POIVRE", "SAGE", "IMMEUBLE", "NUAGE", "VERRE", "POCHETTE", "FLEUR", "ENFANT", "CARNET", "ARMOIRE",
        "MONDE", "POMME", "EFFORT", "SOURIS", "JOURNAL", "SOLEIL", "CAROTTE", "INDE",
        "ESPAGNE", "ISTANBUL", "HOMME", "FEMME", "STYLO", "TORTUE", "MELON", "CHAT",
        "LIVRE", "CHIEN", "OISEAU", "CHOU", "CITRON", "CISEAUX", "TABLE", "BANANE", "AUTOBUS", "CANARD",
        "PERROQUET", "POMMEDETERRE", "AUBERGINE", "FENETRE", "ORANGE", "CONCOMBRE", "CHAISE", "ECUREUIL",
        "OIGNON", "LAIT", "CHAPEAU", "VILLE", "ASSIETTE", "LIEVRE", "TELEPHONE", "TURQUIE", "AVION", "RAISIN",
        "CERISE", "FEUILLE", "LIT", "SERPENT", "YAOURT", "ZEBRE", "OLIVE", "GIRAFE", "ALLEMAGNE",
        "VOITURE", "OURS", "BALLON", "BANQUE", "VELO", "NOIX", "PIN", "SAUTERELLE", "FRAISE",
        "MER", "CREMEGLACEE", "BOUTON", "PAIN", "ELECTRICITE", "HARICOT", "FRANCE", "FUTUR", "LUNETTES",
        "PAMPLEMOUSSE", "TAPIS", "HAMBURGER", "DINDON", "EPINARD", "ANGLETERRE", "ITALIE", "JAPON", "CANADA",
        "PORTE", "PASTEQUE", "AIGLE", "ABRICOT", "BIBLIOTHEQUE", "PONT", "VILLAGE", "GATEAU", "NORD",
        "CIGOGNE", "PORT", "MANDARINE", "BARBECUE", "MEXIQUE", "LENTILLE", "CHENE", "FRUIT", "MAIS",
        "CONVERSATION", "GRENADE", "ARMEE", "FORET", "ARAIGNEE", "PALMIER", "PANTALON", "ARGENT",
        "POULE", "RIZ", "PLAGE", "POLOGNE", "RADIO", "COLORE", "ROME", "REVE", "MONTRE",
        "AIL", "POT", "LEGUME", "CINEMA", "FROID", "RUE", "BALAI", "PARAPLUIE", "CHAMPS",
        "TELEVISION", "CASSEROLE", "CHAUSSURE", "CROCODYLE", "GRAINE", "TOMATE", "TRACTEUR", "TRAIN",
        "TOURISTE", "CHOUXSAUR", "CERFVOLANT", "UNIVERSITE", "BATEAU", "VIENNE", "EVENTAIL", "REPAS",
        "CRABE", "ETOILE", "ROUTE", "GRECE", "BAGUE", "LYS", "DOMMAGE", "CLOCHE", "BOULIER",
        "ETATSUNIS", "AFRIQUE", "DOULEUR", "MEDITERRANEE", "SCORPION", "AQUARIUM", "TRUITE", "AMERIQUE",
        "ANANAS", "ARGENTINE", "EFFRONTE", "ASCENSEUR", "ASIE", "AUSTRALIE", "TOURNESOL", "MIEL",
        "GOMBO", "OUEST", "DRAPEAU", "BELGIQUE", "BLANC", "BILLARD", "BISCUIT", "BLOC", "INSECTE",
        "REGION", "GRAND", "AVENUE", "PARADIS", "FRONT", "REPUBLIQUE", "TENTE", "CHACAL", "BUISSON",
        "SAC", "MARCHE", "MARTEAU", "TCHERKES", "CHOCOLAT", "CIMENT", "CHINE", "CLOU", "DECHET",
        "DENTELLE", "LAURIER", "EQUILIBRE", "RIVIERE", "CHAMEAU", "COUTURE", "LANGUE", "DYNAMO",
        "DENT", "GENOU", "MEDECIN", "PLEIN", "AMI", "LEVRE", "MARIAGE", "MOISSON", "ACIDE",
        "GANT", "ENERGIE", "PRUNE", "ANCIEN", "BLAGUE", "ETIQUETTE", "SEPTEMBRE", "MAROC",
        "LANTERNE", "FESTIVAL", "PLANTE", "IDEE", "ROBE", "REÇU", "PHOQUE", "PHOTO",
        "FREIN", "FOOTBALL", "PROBABLEMENT", "GARAGE", "PLANETE", "ENTREE", "CIEL", "LAC",
        "CHEMISE", "ENGRAIS", "ROSE", "SUD", "BRUIT", "NOUVELLE", "PEUPLE", "ANCHOIS",
        "RECOLTE", "AVIATION", "SERVIETTE", "FANTOME", "HELICOPTERE", "COQ", "GOUVERNEMENT", "TILLEUL",
        "TIEDE", "MOUILLE", "AIGUILLE", "CLIMAT", "VACHE", "CONSTRUCTION", "CORDE", "SQUELETTE",
        "GARE", "HUITRE", "GENDARME", "JAPONAIS", "GUIMAUVE", "JET", "RASOIR", "JUPITER",
        "COURGE", "CABINE", "CAGE", "CAFE", "CACTUS", "TROTTOIR", "TROUSSE", "CAMERA",
        "CANARI", "CANAPE", "COUVERCLE", "NEIGE", "CORBEAU", "FOURMI", "BOUCHER", "CUILLERE",
        "PEUPLIER", "ROCHE", "SKATEBOARD", "CHEVRE", "CEINTURE", "PELLE", "CHATAIGNE", "DECOUVERTE",
        "CHYPRE", "PERSONNE", "KOALA", "FAUTEUIL", "VOISIN", "CONFERENCE", "CONTROLE", "COPIE",
        "PROTECTION", "MOUTON", "COCON", "CHARBON", "SABLE", "TIRELIRE", "GRENOUILLE", "SEC",
        "FRUITSSECS", "BOITE", "PETIT", "MOISISSURE", "CONE", "CULTURE", "RAME", "LAVANDE",
        "LYCEE", "LUXE", "MEDAILLE", "SUBSTANCE", "GROTTE", "PATES", "MATERIAU", "LAITERIE",
        "MAGNOLIA", "CHAMPIGNON", "LAITUE", "CONTE", "BLEU", "MAI", "ASSEMBLEE", "BRISE",
        "ESCALIER", "CENTRE", "SAISON", "MICRO", "MINARET", "INVITE", "RASSEMBLEMENT", "CARACTERE",
        "MOTEUR", "COMPTABILITE", "BOUGIE", "CUISINE", "MUSEE", "LIQUIDE", "MENTHE", "AVRIL",
        "CHICHE", "NORMAL", "NOTE", "POPULATION", "JANVIER", "CHAMBRE", "BOIS", "ECOLE",
        "CANNEPECHE", "OMEGA", "ORGANE", "MILIEU", "HERBE", "HOTEL", "AUTOROUTE", "FROTTER",
        "RECOMPENSE", "MIDI", "ENSEIGNANT", "MESURE", "TRICOT", "EXEMPLE", "COUVERTURE", "SPECIAL",
        "LIBERTE", "MANTEAU", "COTON", "PANDA", "PARAGRAPHE", "PARACHUTE", "DOIGT", "CHAUSSON",
        "PARTAGER", "RIDEAU", "JEUDI", "RAYON", "FROMAGE", "PIDE", "PILE", "POULET",
        "PIANO", "PIZZA", "DISQUE", "POLICE", "PORTUGAL", "BUREAU", "POSTE", "PRATIQUE",
        "TIMBRE", "BOUSSOLE", "ETAGERE", "CONFORTABLE", "RAMADAN", "COULEUR", "IMAGE", "FUSEE",
        "VENT", "HEURE", "SAVON", "SANTE", "CHEWINGGUM", "SALADE", "SALON", "JAUNE",
        "SAVANE", "PAGE", "VOYAGE", "BASSE", "HUIT", "SALUT", "TOI", "SERRE",
        "SILENCIEUX", "NIVEAU", "CHAUD", "BOVIN", "EFFACER", "SYMBOLES", "MOUCHE", "NERF",
        "ABRI", "VINAIGRE", "BRUME", "SITE", "NOIR", "SODA", "RESPIRATION", "FIN",
        "AUTOMNE", "QUESTION", "SOCIAL", "LIGNEE", "MOT", "SPORT", "EAU", "IRRIGATION",
        "PRESENTATION", "CARAFE", "DUREE", "EXIL", "AUBE", "FAUCON", "ECHARPE", "SHAMPOOING",
        "CHANSON", "BANDE", "POEME", "BOUTEILLE", "EQUIPE", "DEMANDE", "COMPLET", "GRANULEUX",
        "CHAR", "PEIGNE", "HISTOIRE", "DESIGN", "PLAFOND", "RECOMMANDATION", "TYPHON", "ROUE",
        "DROITSAUTEUR", "PROPRE", "PANTOUFLE", "LIVRAISON", "MERCI", "FAUX", "COMMERCE", "THEATRE",
        "BALLE", "TOUPIE", "TRAFIC", "TOURISME", "CORNICHON", "COLLE", "SEL", "FUSIL",
        "TOUT", "TUBE", "CERFVOLANT", "SOMMEIL", "FRAIS", "PAYS", "UNITE", "PRODUCTION",
        "HAUT", "VASE", "PARENT", "TAXE", "VIDEO", "VIRAGE", "GRIOTTE", "VOLCAN",
        "ACCENT", "PLUIE", "RUBIS", "MENSONGE", "PENTE", "INCENDIE", "CHAUVESOURIS", "OREILLER",
        "VIE", "AUTEUR", "AIGUILLE", "LIEU", "VERT", "ANNEE", "COMMENTAIRE", "GREC",
        "CHARGE", "VISAGE", "TEMPS", "AGRICULTURE", "DIFFICILE", "GROUPE"
    ],
    es: [
        "ARBOL", "FAMILIA", "MENTE", "ORO", "PERA", "LEON", "ESPEJO", "PEZ", "BALCON", "BEBE",
        "PIMIENTA", "SABIO", "EDIFICIO", "NUBE", "VIDRIO", "BOLSILLO", "FLOR", "NIÑO", "CUADERNO", "ARMARIO",
        "MUNDO", "MANZANA", "ESFUERZO", "RATON", "ELEFANTE", "PERIODICO", "SOL", "ZANAHORIA", "SUEÑO",
        "ESPAÑA", "ESTAMBUL", "HOMBRE", "MUJER", "BOLIGRAFO", "TORTUGA", "HORMIGA", "SANDIA", "GATO",
        "LIBRO", "PERRO", "PAJARO", "COL", "LIMON", "TIJERAS", "MESA", "PLATANO", "AUTOBUS", "PATO",
        "LORO", "PAPA", "BERENJENA", "VENTANA", "NARANJA", "PEPINO", "SILLA", "ARDILLA",
        "CEBOLLA", "LECHE", "SOMBRERO", "CIUDAD", "PLATO", "CONEJO", "TELEFONO", "TURQUIA", "AVION", "UVA",
        "CEREZA", "HOJA", "CAMA", "SERPIENTE", "YOGUR", "CEBRA", "ACEITUNA", "JIRAFA",
        "COCHE", "OSO", "BALON", "BANCO", "BICICLETA", "NUEZ", "PINO", "GRILLO", "FRESA",
        "MAR", "HELADO", "BOTON", "PAN", "ELECTRICIDAD", "FRIJOL", "FRANCIA", "FUTURO",
        "GAFAS", "TORONJA", "ALFOMBRA", "HAMBURGUESA", "PAVO", "ESPINACA", "INGLATERRA", "ITALIA",
        "JAPON", "CANADA", "PUERTA", "AGUILA", "ALBARICOQUE", "ESTANTE", "PUENTE", "PUEBLO",
        "GALLETA", "NORTE", "CIGUEÑA", "PUERTO", "MANDARINA", "BARBACOA", "MEXICO", "LENTEJA",
        "ROBLE", "FRUTA", "MAIZ", "CONVERSACION", "GRANADA", "EJERCITO", "BOSQUE", "ARAÑA",
        "PALMERA", "PANTALON", "MARGARITA", "DINERO", "POLLO", "ARROZ", "PLAYA", "POLONIA",
        "RADIO", "COLORIDO", "ROMA", "RELOJ", "AJO", "MACETA", "VERDURA", "CINE",
        "FRIO", "CALLE", "ESCOBA", "PARAGUAS", "CAMPO", "TELEVISION", "CAZUELA", "ZAPATO",
        "COCODRILO", "SEMILLA", "TRACTOR", "TREN", "TURISTA", "CHUCRUT", "COMETA", "UNIVERSIDAD",
        "BARCO", "VIENA", "ABANICO", "COMIDA", "CANGREJO", "ESTRELLA", "CAMINO", "GRECIA",
        "ANILLO", "LIRIO", "DAÑO", "ACEITE", "CAMPANA", "ABACO", "ESTADOSUNIDOS", "DOLOR",
        "MEDITERRANEO", "ESCORPION", "ACUARIO", "TRUCHA", "AMERICA", "PIÑA", "ARGENTINA",
        "DESCARADO", "ASCENSOR", "ASIA", "AUSTRALIA", "GIRASOL", "MIEL", "BALCANES", "QUINGOMBO",
        "OESTE", "BANDERA", "BELGICA", "BLANCO", "BILLAR", "BLOQUE", "INSECTO", "REGION",
        "GRANDE", "AVENIDA", "PARAISO", "FRENTE", "REPUBLICA", "TIENDA", "CHACAL", "ARBUSTO",
        "BOLSO", "MERCADO", "MARTILLO", "CIRCASICO", "CHOCOLATE", "CEMENTO", "CHINA", "CLAVO",
        "BASURA", "ENCAJE", "LAUREL", "JOVEN", "EQUILIBRIO", "RIO", "CAMELLO", "COSER",
        "LENGUA", "DINAMO", "DIENTE", "RODILLA", "MEDICO", "LLENO", "AMIGO", "LABIO",
        "BODA", "COSECHA", "ACIDO", "GUANTE", "ENERGIA", "CIRUELA", "VIEJO", "BROMA",
        "ETIQUETA", "SEPTIEMBRE", "MARRUECOS", "FAROL", "FESTIVAL", "PLANTULA", "IDEA",
        "VESTIDO", "RECIBO", "FOCA", "FOTO", "FRENO", "FUTBOL", "PROBABLEMENTE", "GARAJE",
        "PLANETA", "ENTRADA", "CIELO", "LAGO", "CAMISA", "ABONO", "ROSA", "PLATA",
        "SUR", "RUIDO", "NOTICIA", "ANCHOA", "MAPA", "AVIACION", "TOALLA", "FANTASMA",
        "HELICOPTERO", "GALLO", "GOBIERNO", "TILO", "TIBIO", "MOJADO", "AGUJA", "CLIMA",
        "VACA", "CONSTRUCCION", "CUERDA", "ESQUELETO", "ESTACION", "OSTRA", "GENDARME", "JAPONES",
        "GOMINA", "JET", "MAQUINILLA", "JUPITER", "CALABAZA", "CABINA", "JAULA", "CAFE",
        "CACTUS", "ACERA", "ESTUCHE", "CORAZON", "CAMARA", "CANARIO", "SOFA", "TAPA",
        "NIEVE", "NEGRO", "CUERVO", "TARJETA", "CARNICERO", "CUCHARA", "ALAMO", "ROCA",
        "MONOPATIN", "CABRA", "CINTURON", "PALA", "CASTAÑA", "DESCUBRIMIENTO", "CHIPRE",
        "PERSONA", "KOALA", "SILLON", "VECINO", "CONFERENCIA", "CONTROL", "COPIA", "PROTECCION",
        "OVEJA", "CAPULLO", "CARBON", "ARENA", "ALCANCÍA", "RANA", "SECO", "FRUTOSSECOS",
        "CAJA", "PEQUEÑO", "MOHO", "CONO", "CULTURA", "REMAR", "LAVANDA", "LICEO",
        "LUJO", "MEDALLA", "SUSTANCIA", "CUEVA", "PASTA", "MATERIAL", "LECHERIA", "MAGNOLIA",
        "HONGO", "LECHUGA", "CUENTO", "AZUL", "MAYO", "ASAMBLEA", "BRISA", "ESCALERA",
        "CENTRO", "TEMPORADA", "MICROFONO", "MINARETE", "INVITADO", "REUNION", "CARACTER",
        "MOTOR", "CONTABILIDAD", "VELA", "COCINA", "MUSEO", "EFECTIVO", "MENTA", "ABRIL",
        "GARBANZO", "NORMAL", "NOTA", "POBLACION", "ENERO", "HABITACION", "MADERA", "ESCUELA",
        "CAÑADEPESCAR", "OMEGA", "ORGANO", "MEDIO", "HIERBA", "HOTEL", "AUTOPISTA", "FROTAR",
        "RECOMPENSA", "MEDIODIA", "MAESTRO", "MEDIDA", "TEJIDO", "EJEMPLO", "COBERTURA", "ESPECIAL",
        "LIBERTAD", "ABRIGO", "ALGODON", "PANDA", "PARRAFO", "PARACAIDAS", "DEDO", "ZAPATILLA",
        "COMPARTIR", "CORTINA", "JUEVES", "PANAL", "QUESO", "PIDE", "PILA", "PIANO",
        "PIZZA", "DISCO", "POLICIA", "PORTUGAL", "OFICINA", "CORREOS", "BOLSA", "PRACTICO",
        "SELLO", "BRUJULA", "COMODO", "COLOR", "IMAGEN", "SECCION", "COHETE", "VIENTO",
        "HORA", "JABON", "SALUD", "CHICLE", "ENSALADA", "SALON", "AMARILLO", "SABANA",
        "PAGINA", "VIAJE", "AUXILIAR", "OCHO", "SALUDO", "TU", "INVERNADERO", "SILENCIOSO",
        "NIVEL", "CALIENTE", "BOVINO", "BORRAR", "SIMBOLOS", "MOSCA", "NERVIOSO", "REFUGIO",
        "VINAGRE", "NIEBLA", "SITIO", "SODA", "RESPIRACION", "FIN", "OTOÑO", "PREGUNTA",
        "SOCIAL", "LINAJE", "PALABRA", "DEPORTE", "AGUA", "RIEGO", "PRESENTACION", "GARRAFA",
        "DURACION", "EXILIO", "AMANECER", "HALCON", "BUFANDA", "CHAMPU", "CANCION", "FRANJA",
        "POEMA", "BOTELLA", "EQUIPO", "DEMANDA", "COMPLETO", "GRANULADO", "TANQUE", "PEINE",
        "HISTORIA", "DISEÑO", "TECHO", "RECOMENDACION", "TIFON", "RUEDA", "DERECHOSAUTOR", "LIMPIO",
        "OLLA", "PANTUFLAS", "ENTREGA", "GRACIAS", "GUADAÑA", "COMERCIO", "TEATRO", "PELOTA",
        "TROMPO", "TIERRA", "TRAFICO", "TURISMO", "PEPINILLO", "COLA", "SAL", "RIFLE",
        "TODO", "TUBO", "BARATO", "TARIFA", "PAIS", "UNIDAD", "PRODUCCION", "ARRIBA",
        "JARRON", "PADRE", "IMPUESTO", "VIDEO", "CURVA", "GUINDA", "VOLCAN", "ENFASIS",
        "LLUVIA", "RUBI", "MENTIRA", "PENDIENTE", "INCENDIO", "MURCIELAGO", "ALMOHADA", "VIDA",
        "AGUJA", "LUGAR", "VERDE", "AÑO", "COMENTARIO", "HUEVO", "GRIEGO", "CARGA",
        "ROSTRO", "TIEMPO", "AGRICULTURA", "DIFICIL", "GRUPO"
    ],
    ru: [
        "ДЕРЕВО", "СЕМЬЯ", "РАЗУМ", "ЗОЛОТО", "ГРУША", "ЛЕВ", "ЗЕРКАЛО", "РЫБА", "БАЛКОН", "МАЛЫШ",
        "ПЕРЕЦ", "МУДРЕЦ", "ЗДАНИЕ", "ОБЛАКО", "СТЕКЛО", "КАРМАН", "ЦВЕТОК", "РЕБЕНОК", "ТЕТРАДЬ", "ШКАФ",
        "МИР", "ЯБЛОКО", "ТРУД", "МЫШЬ", "СЛОН", "ГАЗЕТА", "СОЛНЦЕ", "МОРКОВЬ", "МЕЧТА", "ИНДИЯ",
        "ИСПАНИЯ", "СТАМБУЛ", "ЧЕЛОВЕК", "ЖЕНЩИНА", "РУЧКА", "ЧЕРЕПАХА", "МУРАВЕЙ", "АРБУЗ", "КОТ",
        "КНИГА", "СОБАКА", "ПТИЦА", "КАПУСТА", "ЛИМОН", "НОЖНИЦЫ", "СТОЛ", "БАНАН", "АВТОБУС", "УТКА",
        "ПОПУГАЙ", "КАРТОФЕЛЬ", "БАКЛАЖАН", "ОКНО", "АПЕЛЬСИН", "ОГУРЕЦ", "СТУЛ", "БЕЛКА",
        "ЛУК", "МОЛОКО", "ШЛЯПА", "ГОРОД", "ТАРЕЛКА", "КРОЛИК", "ТЕЛЕФОН", "ТУРЦИЯ", "САМОЛЁТ", "ВИНОГРАД",
        "ВИШНЯ", "ЛИСТ", "КРОВАТЬ", "ЗМЕЯ", "ЙОГУРТ", "ЗЕБРА", "ОЛИВКА", "ЖИРАФ", "ГЕРМАНИЯ",
        "АНКАРА", "АНТАЛИЯ", "МАШИНА", "МЕДВЕДЬ", "ВОЗДУШНЫЙ ШАР", "БАНК", "ВЕЛОСИПЕД", "БОЛГАРИЯ", "ГРЕЦКИЙ ОРЕХ",
        "СОСНА", "ЧАНАККАЛЕ", "КУЗНЕЧИК", "КЛУБНИКА", "МОРЕ", "ДОЛМАБАХЧЕ", "МОРОЖЕНОЕ", "ПУГОВИЦА", "ХЛЕБ",
        "ЭЛЕКТРИЧЕСТВО", "ФАСОЛЬ", "ФРАНЦИЯ", "ОЧКИ", "ГРЕЙПФРУТ", "КОВЁР", "ГАМБУРГЕР", "ИНДЕЙКА",
        "ШПИНАТ", "АНГЛИЯ", "ИТАЛИЯ", "ЯПОНИЯ", "КАНАДА", "ДВЕРЬ", "ДЫНЯ", "ОРЁЛ",
        "АБРИКОС", "ЧЕРЕШНЯ", "КНИЖНАЯ ПОЛКА", "МОСТ", "ДЕРЕВНЯ", "ПЕЧЕНЬЕ", "СЕВЕР", "АИСТ", "ПОРТ",
        "МАНДАРИН", "МАНГАЛ", "МЕКСИКА", "ЧЁЧЕВИЦА", "ДУБ", "КУКУРУЗА", "БЕСЕДА", "ГРАНАТ",
        "АРМИЯ", "ЛЕС", "АВТОМОБИЛЬ", "ПАУК", "ПАЛЬМА", "БРЮКИ", "РОМАШКА", "ДЕНЬГИ",
        "КУРИЦА", "РИС", "ПЛЯЖ", "ПОЛЬША", "РАДИО", "ЦВЕТНОЙ", "РИМ", "ЧАСЫ", "САМСУН",
        "САПАНДЖА", "ЧЕСНОК", "ГОРШОК", "ОВОЩ", "СЕРПИЛ", "ЧИЛИ", "ХОЛОД", "УЛИЦА",
        "МЕТЛА", "ЗОНТ", "ШИРИНДЖЕ", "ПОЛЕ", "ТЕКИРДАГ", "ТЕЛЕВИЗОР", "КАСТРЮЛЯ", "ТАПОЧКИ",
        "КРОКОДИЛ", "СЕМЯ", "ПОМИДОР", "ТРАБЗОН", "ТРАКТОР", "ПОЕЗД", "ТУРИСТ", "СОЛЁНИЕ",
        "ВОЗДУШНЫЙ ЗМЕЙ", "УЛУДАГ", "УНИВЕРСИТЕТ", "ВАН", "ПАРОМ", "ВЕНА", "ЯЛОВА",
        "ВЕЕР", "ЕДА", "КРАБ", "ЗВЕЗДА", "ДОРОГА", "ГРЕЦИЯ", "КОЛЬЦО", "ЛИЛИЯ",
        "ВРЕД", "ОЛИВКОВОЕ МАСЛО", "КОЛОКОЛ", "АБАК", "ОГУРЧИК", "АДАНА", "АФРИКА", "АГРЫ",
        "СРЕДИЗЕМНОМОРЬЕ", "СКОРПИОН", "АКВАРИУМ", "ФОРЕЛЬ", "АЛИ", "АМЕРИКА", "АНАНАС", "АНИТКАБИР",
        "АРАБ", "АРГЕНТИНА", "НАГЛЫЙ", "ЛИФТ", "АЗИЯ", "АВСТРАЛИЯ", "ПОДСОЛНЕЧНИК", "АЗЕРБАЙДЖАН",
        "МЁД", "БАЛКАНЫ", "БАМИЯ", "БАНВИТ", "СТАКАН", "ЗАПАД", "ФЛАГ", "БЕЛЬГИЯ", "БЕЛЫЙ",
        "БИЛЬЯРД", "ПЕЧЕНЬЕ", "БЛОК", "НАСЕКОМОЕ", "РЕГИОН", "БОЛЬШОЙ", "ПРОСПЕКТ", "РАЙ",
        "ФАСАД", "РЕСПУБЛИКА", "ПАЛАТКА", "ШАКАЛ", "КУСТ", "СУМКА", "БАЗАР", "МОЛОТОК",
        "ЧЕРКЕС", "ШОКОЛАД", "ЦЕМЕНТ", "ГВОЗДЬ", "МУСОР", "КРУЖЕВО", "ЛАВР", "ЮНОША",
        "БАЛАНС", "РУЧЕЙ", "ВЕРБЛЮД", "ШИТЬЁ", "ЯЗЫК", "ДИНАМО", "ЗУБ", "КОЛЕНО",
        "ДОКТОР", "ПОЛНЫЙ", "ДРУГ", "ГУБА", "СВАДЬБА", "ЭФЕС", "ПОСЕВ", "КИСЛЫЙ",
        "ПЕРЧАТКА", "ЭМИНЁНЮ", "ЭНЕРГИЯ", "СЛИВА", "СТАРЫЙ", "ШУТКА", "ЭТИКЕТКА", "СЕНТЯБРЬ",
        "МАРОККО", "ФОНАРЬ", "ФЕСТИВАЛЬ", "САЖЕНЕЦ", "МЫСЛЬ", "ПЛАТЬЕ", "КВИТАНЦИЯ", "ТЮЛЕНЬ", "ФОТОГРАФИЯ",
        "ТОРМОЗ", "ФУТБОЛ", "ВОЗМОЖНО", "ГАРАЖ", "ПЛАНЕТА", "ВХОД", "НЕБО", "ОЗЕРО",
        "РУБАШКА", "УДОБРЕНИЕ", "РОЗА", "СЕРЕБРО", "ЮГ", "ШУМ", "НОВОСТЬ", "НАРОД",
        "ХАМСИ", "КАРТА", "УРОЖАЙ", "АВИАЦИЯ", "ПОЛОТЕНЦЕ", "ПРИЗРАК", "ВЕРТОЛЁТ", "ПЕТУХ",
        "ПРАВИТЕЛЬСТВО", "ЛИПА", "ТЕПЛЫЙ", "РЕКА", "МОКРЫЙ", "ИГЛА", "КЛИМАТ", "КОРОВА",
        "СТРОИТЕЛЬСТВО", "ВЕРЁВКА", "СКЕЛЕТ", "ВОКЗАЛ", "УСТРИЦА", "ЖАНДАРМ", "ЯПОНЕЦ", "ЖЕВАТЕЛЬНАЯ РЕЗИНКА",
        "РЕАКТИВНЫЙ САМОЛЁТ", "БРИТВА", "ЮПИТЕР", "ТЫКВА", "КАЮТА", "КЛЕТКА", "КОФЕ", "КАКТУС",
        "ТРОТУАР", "ПЕНАЛ", "СЕРДЦЕ", "КАМЕРА", "КАНАРЕЙКА", "ДИВАН", "КРЫШКА", "СНЕГ",
        "ВОРОН", "КАССИР", "ЛОЖКА", "ТОПОЛЬ", "СКАЛА", "КЕЙК", "КАЗАХСТАН", "КОЗА",
        "РЕМЕНЬ", "КОВШ", "КАШТАН", "ОТКРЫТИЕ", "КИПР", "КИЛИМ", "ЛИЧНОСТЬ", "КОАЛА",
        "КРЕСЛО", "СОСЕД", "КОНФЕРЕНЦИЯ", "КОНТРОЛЬ", "КОПИЯ", "ЗАЩИТА", "КОЗЁЛ", "КОКОН",
        "УГОЛЬ", "ПЕСОК", "КОПИЛКА", "ОБУВЬ", "ЛЯГУШКА", "СУХОЙ", "ОРЕХИ", "КОРОБКА",
        "МАЛЕНЬКИЙ", "ПЛЕСЕНЬ", "КОНУС", "КУЛЬТУРА", "ГРЕБЛЯ", "ЛАВАНДА", "ЛИЦЕЙ", "РОСКОШЬ",
        "МЕДАЛЬ", "ВЕЩЕСТВО", "ПЕЩЕРА", "МАКАРОНЫ", "МАТЕРИАЛ", "МОЛОЧНАЯ", "МАГНОЛИЯ", "ГРИБ",
        "САЛАТ", "СКАЗКА", "СИНИЙ", "МАЙ", "ПАРЛАМЕНТ", "БРИЗ", "ЛЕСТНИЦА", "ЦЕНТР",
        "СЕЗОН", "МИКРОФОН", "МИНАРЕТ", "ГОСТЬ", "МИТИНГ", "ХАРАКТЕР", "ДВИГАТЕЛЬ", "БУХГАЛТЕРИЯ",
        "СВЕЧА", "КУХНЯ", "МУЗЕЙ", "НАЛИЧНЫЕ", "МЯТА", "РЕЧКА", "НИГДЕ", "АПРЕЛЬ",
        "НУТ", "НОРМА", "ЗАМЕТКА", "НАСЕЛЕНИЕ", "ЯНВАРЬ", "КОМНАТА", "ДЕРЕВО", "ШКОЛА",
        "УДОЧКА", "ОМЕГА", "ОРГАН", "СЕРЕДИНА", "ТРАВА", "ОТЕЛЬ", "ШОССЕ", "НАГРАДА",
        "ПОЛДЕНЬ", "УЧИТЕЛЬ", "МЕРКА", "ВЯЗАНИЕ", "ПРИМЕР", "ПОКРЫВАЛО", "ОСОБЕННЫЙ", "СВОБОДА",
        "ПАЛЬТО", "ХЛОПОК", "ПАНДА", "ПАРАГРАФ", "ПАРАШЮТ", "ПАЛЕЦ", "ТАПОЧКИ", "ДЕЛИТЬСЯ",
        "ШТОРА", "ЧЕТВЕРГ", "СОТЫ", "СЫР", "ПИТА", "БАТАРЕЯ", "ФОРТЕПИАНО", "ПИЦЦА",
        "ПЛАСТИНКА", "ПОЛИЦИЯ", "ПОРТУГАЛИЯ", "ПОЧТА", "ПАКЕТ", "ПРАКТИЧНЫЙ", "КОМПАС", "ПОЛКА",
        "УДОБНЫЙ", "РАМАДАН", "ЦВЕТ", "КАРТИНА", "ОТДЕЛ", "РАКЕТА", "ВЕТЕР", "МЫЛО",
        "ЗДОРОВЬЕ", "ЖВАЧКА", "САЛАТ", "ЗАЛ", "ЛОДКА", "ЖЁЛТЫЙ", "СТРАНИЦА", "ПОЕЗДКА",
        "ЖУРНАЛ", "ВОСЕМЬ", "ПРИВЕТ", "ТЫ", "ТЕПЛИЦА", "ТИХИЙ", "УРОВЕНЬ", "ТЕПЛО", "СКОТ",
        "СТИРАТЬ", "СИМВОЛЫ", "МУХА", "НЕРВ", "УКРЫТИЕ", "УКСУС", "ТУМАН", "МЕСТО",
        "ЧЁРНЫЙ", "ГАЗИРОВКА", "ДЫХАНИЕ", "КОНЕЦ", "ОСЕНЬ", "ВОПРОС", "СОЦИАЛЬНЫЙ", "РОД",
        "СЛОВО", "СПОРТ", "ВОДА", "ПОЛИВ", "ПРЕЗЕНТАЦИЯ", "КУВШИН", "ПРОДОЛЖИТЕЛЬНОСТЬ", "ИЗГНАНИЕ",
        "РАССВЕТ", "ЯСТРЕБ", "ШАРФ", "ШАМПУНЬ", "ШАНЛЫУРФА", "ПЕСНЯ", "ЛЕНТА", "СТИХ",
        "БУТЫЛКА", "КОМАНДА", "ТРЕБОВАНИЕ", "ПОЛНЫЙ", "ТАНК", "РАСЧЁСКА", "ИСТОРИЯ", "ДИЗАЙН",
        "ПОТОЛОК", "СОВЕТ", "ТАЙФУН", "КОЛЕСО", "АВТОРСКОЕ ПРАВО", "ЧИСТЫЙ", "ДОСТАВКА", "СПАСИБО",
        "КОСА", "ТОРГОВЛЯ", "ТЕАТР", "ТОКАТ", "МЯЧ", "ВОЛЧОК", "ПОЧВА", "ДВИЖЕНИЕ",
        "ТУРИЗМ", "КЛЕЙ", "СОЛЬ", "РУЖЬЁ", "ВСЁ", "ТРУБА", "ДЕШЁВЫЙ", "СОН", "ПЛАТА",
        "СТРАНА", "ЕДИНИЦА", "ПРОИЗВОДСТВО", "ВЕРХ", "ВАЗА", "РОДИТЕЛЬ", "НАЛОГ", "ВИДЕО",
        "ПОВОРОТ", "ВУЛКАН", "УДАРЕНИЕ", "ДОЖДЬ", "РУБИН", "ЛОЖЬ", "СКЛОН", "ПОЖАР",
        "ЛЕТУЧАЯ МЫШЬ", "ПОДУШКА", "ЖИЗНЬ", "ПИСАТЕЛЬ", "ПАРУС", "СТРЕЛКА", "МЕСТО", "ЗЕЛЁНЫЙ",
        "ГОД", "КОММЕНТАРИЙ", "ЯЙЦО", "ГРЕК", "ГРУЗ", "ЛИЦО", "ВРЕМЯ", "СЕЛЬСКОЕ ХОЗЯЙСТВО",
        "ТРУДНЫЙ", "ГРУППА"
    ]
};

export { words };
