const words = {
    tr: [
        "ANNE", "BABA", "KARDEŞ", "EV", "ARABA", "SU", "YEMEK", "İÇMEK", "GİTMEK", "GELMEK",
        "OKUL", "KİTAP", "KALEM", "DEFTER", "ÖĞRETMEN", "ARKADAŞ", "İŞ", "PARA", "ZAMAN", "GÜN",
        "GECE", "SABAH", "AKŞAM", "HAVA", "GÜNEŞ", "AY", "YILDIZ", "DENİZ", "DAĞ", "ORMAN",
        "ÇİÇEK", "AĞAÇ", "KUŞ", "KEDİ", "KÖPEK", "EL", "AYAK", "BAŞ", "GÖZ", "KULAK",
        "SEVGİ", "MUTLU", "ÜZGÜN", "İYİ", "KÖTÜ", "BÜYÜK", "KÜÇÜK", "UZUN", "KISA", "HIZLI",
        "YAVAŞ", "GÜZEL", "ÇİRKİN", "SICAK", "SOĞUK", "YAĞMUR", "KAR", "RÜZGAR", "BULUT", "SİS",
        "YOL", "KAPI", "PENCERE", "ODA", "MASA", "SANDALYE", "YATAK", "DOLAP", "AYNA", "SAAT",
        "TELEFON", "BİLGİSAYAR", "TELEVİZYON", "RADYO", "MÜZİK", "FİLM", "OYUN", "SPOR", "FUTBOL", "BASKETBOL",
        "KOŞMAK", "YÜZMEK", "ATLAMAK", "DANS", "ŞARKI", "SES", "GÜRÜLTÜ", "SAKİN", "KALABALIK", "BOŞ",
        "DOLU", "TEMİZ", "KİRLİ", "YENİ", "ESKİ", "RENK", "KIRMIZI", "MAVİ", "YEŞİL", "SARI",
        "SİYAH", "BEYAZ", "GRİ", "MOR", "TURUNCU", "PEMBE", "KAHVERENGİ", "ALTIN", "GÜMÜŞ", "TAŞ",
        "TOPRAK", "KUM", "ÇAKIL", "ÇİMEN", "BAHÇE", "PARK", "SOKAK", "CADDE", "KÖPRÜ", "NEHİR",
        "GÖL", "DALGA", "BALIK", "YENGEÇ", "KAPLUMBAĞA", "TAVUK", "HOROZ", "İNEK", "KOYUN", "KEÇİ",
        "AT", "EŞEK", "FARE", "YILAN", "ÖRÜMCEK", "BÖCEK", "ARI", "KELEBEK", "SİNEK", "KURBAĞA",
        "ET", "TAVUK", "BALIK", "EKMEK", "PEYNİR", "ZEYTİN", "YUMURTA", "SÜT", "YOĞURT", "TEREYAĞI",
        "ÇAY", "KAHVE", "SU", "MEYVE", "ELMA", "ARMUT", "ÜZÜM", "PORTAKAL", "MANDALİNA", "MUZ",
        "ÇİLEK", "KİRAZ", "KARPUZ", "KAVUN", "ŞEFTALİ", "KAYISI", "ERİK", "NAR", "İNCİR", "HURMA",
        "SEBZE", "DOMATES", "SALATALIK", "BİBER", "PATATES", "SOĞAN", "SARIMSAK", "HAVUÇ", "LAHANA", "MARUL",
        "ISPANAK", "FASULYE", "NOHUT", "MERCİMEK", "PİRİNÇ", "MAKARNA", "ÇORBA", "SALATA", "TATLI", "KEK",
        "KURABİYE", "DONDURMA", "ÇİKOLATA", "ŞEKER", "TUZ", "BİBER", "YAĞ", "UN", "SU", "İÇECEK",
        "BARDAK", "TABAK", "KAŞIK", "ÇATAL", "BIÇAK", "KASE", "TENCERE", "TAVA", "FIRIN", "BUZDOLABI",
        "ÇAMAŞIR", "SABUN", "ŞAMPUAN", "DİŞ", "MACUN", "FIRÇA", "HAVLU", "TARAK", "AYAKKABI", "ÇORAP",
        "PANTOLON", "GÖMLEK", "KAZAK", "CEKET", "MONT", "ŞAPKA", "BERE", "ELDİVEN", "KEMER", "ÇANTA",
        "CÜZDAN", "ANAHTAR", "KİLİT", "KAPI", "DUVAR", "ÇATI", "ZEMİN", "MERDİVEN", "ASANSÖR", "BALKON",
        "PERDE", "HALI", "KOLTUK", "KANEPE", "YASTIK", "BATTANİYE", "ÇARŞAF", "UYKU", "RÜYA", "UYANMAK",
        "ÇALIŞMAK", "DİNLENMEK", "OKUMAK", "YAZMAK", "ÇİZMEK", "BOYAMAK", "KONUŞMAK", "DİNLEMEK", "ANLAMAK", "SORMAK",
        "CEVAP", "SORU", "DOĞRU", "YANLIŞ", "BELKİ", "TABİİ", "ELBETTE", "ASLA", "HİÇ", "HER",
        "BAZI", "BİRAZ", "ÇOK", "AZ", "TAMAM", "EVET", "HAYIR", "LÜTFEN", "TEŞEKKÜR", "RİCA",
        "AFEDERSİNİZ", "PARDON", "MERHABA", "SELAM", "HOŞÇAKAL", "GÜLE", "İYİ", "KÖTÜ", "HASTA", "SAĞLIK",
        "DOKTOR", "HASTANE", "İLAÇ", "ATEŞ", "SOĞUK", "SICAK", "AĞRI", "YARA", "KAN", "BAŞ",
        "KALP", "AKCİĞER", "MİDE", "KOL", "BACAK", "PARMAK", "TIRNAK", "SAÇ", "SAKAL", "BIYIK",
        "GÖZLÜK", "KULAKLIK", "ŞEMSİYE", "YAĞMURLUK", "GÜNEŞ", "GÖLGE", "SICAKLIK", "DERECE", "HAVA", "MEVSİM",
        "İLKBAHAR", "YAZ", "SONBAHAR", "KIŞ", "AY", "HAFTA", "YIL", "DÜN", "BUGÜN", "YARIN",
        "ŞİMDİ", "SONRA", "ÖNCE", "ERKEN", "GEÇ", "DAKİKA", "SAAT", "GÜN", "AY", "YIL",
        "DOĞUM", "ÖLÜM", "YAŞ", "GENÇ", "YAŞLI", "BEBEK", "ÇOCUK", "YETİŞKİN", "AİLE", "TEYZE",
        "AMCA", "DAYI", "HALA", "DEDE", "NİNE", "TORUN", "EŞ", "KOCA", "KARI", "NİŞANLI",
        "DÜĞÜN", "EVLİLİK", "BOŞANMA", "AŞK", "NEFRET", "KORKU", "UMUT", "HAYAL", "GERÇEK", "YALAN",
        "SIR", "HEDİYE", "SÜRPRİZ", "TEBRİK", "KUTLAMA", "BAYRAM", "YILBAŞI", "TATİL", "GEZİ", "SEYAHAT",
        "UÇAK", "TREN", "OTOBÜS", "TAKSİ", "BİSİKLET", "YÜRÜMEK", "DURMAK", "BEKLEMEK", "BAŞLAMAK", "BİTMEK",
        "DEĞİŞMEK", "KALMAK", "AYRILMAK", "BULUŞMAK", "TANIŞMAK", "YARDIM", "DESTEK", "PAYLAŞMAK", "ALMAK", "VERMEK",
        "SATMAK", "SATIN", "FİYAT", "UCUZ", "PAHALI", "MAĞAZA", "MARKET", "PAZAR", "DÜKKAN", "KASİYER",
        "MÜŞTERİ", "KALİTE", "MİKTAR", "AĞIRLIK", "BOYUT", "ŞEKİL", "YUVARLAK", "KARE", "ÜÇGEN", "DÜZ",
        "EĞRİ", "DAR", "GENİŞ", "DERİN", "SIĞ", "YÜKSEK", "ALÇAK", "YAKIN", "UZAK", "SAĞ",
        "SOL", "ÖN", "ARKA", "YAN", "İÇ", "DIŞ", "ÜST", "ALT", "ORTA", "KENAR",
        "YER", "MEKAN", "ADRES", "HARİTA", "YOL", "TRAFİK", "ARABA", "KAMYON", "MOTOSİKLET", "SİNYAL",
        "LAMBA", "IŞIK", "KARANLIK", "GÖLGE", "AYNA", "CAM", "METAL", "PLASTİK", "KAĞIT", "KARTON",
        "TAHTA", "BETON", "TUĞLA", "BOYA", "FIRÇA", "ÇEKİÇ", "ÇİVİ", "VİDA", "ALET", "MAKİNE",
        "ELEKTRİK", "PİL", "KABLO", "PRİZ", "DÜĞME", "AÇMAK", "KAPAMAK", "KIRMAK", "TAMİR", "YAPMAK",
        "BOZMAK", "KESMEK", "YAPIŞTIRMAK", "BAĞLAMAK", "ÇÖZMEK", "DİKİŞ", "İĞNE", "İPLİK", "KUMAŞ", "DERİ",
        "YÜN", "PAMUK", "İPEK", "DÜĞME", "FERMUAR", "DESEN", "ÇİZGİ", "NOKTA", "DAİRE", "KÜP",
        "SİLİNDİR", "TOP", "KUTU", "PAKET", "ÇANTA", "VALİZ", "AĞIRLIK", "ÖLÇMEK", "METRE", "KİLOMETRE",
        "GRAM", "KİLOGRAM", "LİTRE", "SIVI", "KATI", "GAZ", "BUHAR", "DUMAN", "ATEŞ", "YANMAK",
        "SÖNMEK", "ISI", "ENERJİ", "GÜÇ", "HIZ", "YAVAŞ", "DENGE", "DÜŞMEK", "KALKMAK", "TAŞIMAK"
    ],
    en: [
        "APPLE", "BALL", "CAT", "DOG", "EGG", "FISH", "GIRL", "BOY", "HOUSE", "CAR",
        "WATER", "MILK", "BREAD", "CHEESE", "MEAT", "FRUIT", "ORANGE", "BANANA", "GRAPE", "PEAR",
        "TABLE", "CHAIR", "DOOR", "WINDOW", "ROOM", "BED", "CLOCK", "PHONE", "BOOK", "PEN",
        "PAPER", "SCHOOL", "TEACHER", "STUDENT", "FRIEND", "WORK", "MONEY", "TIME", "DAY", "NIGHT",
        "MORNING", "EVENING", "SUN", "MOON", "STAR", "SKY", "CLOUD", "RAIN", "SNOW", "WIND",
        "TREE", "FLOWER", "BIRD", "HORSE", "COW", "SHEEP", "GOAT", "PIG", "CHICKEN", "DUCK",
        "HAND", "FOOT", "HEAD", "EYE", "EAR", "NOSE", "MOUTH", "HAIR", "ARM", "LEG",
        "LOVE", "HAPPY", "SAD", "GOOD", "BAD", "BIG", "SMALL", "LONG", "SHORT", "FAST",
        "SLOW", "PRETTY", "UGLY", "HOT", "COLD", "WARM", "COOL", "WET", "DRY", "SOFT",
        "HARD", "LOUD", "QUIET", "CLEAN", "DIRTY", "NEW", "OLD", "RED", "BLUE", "GREEN",
        "YELLOW", "BLACK", "WHITE", "GRAY", "PURPLE", "PINK", "BROWN", "GOLD", "SILVER", "STONE",
        "SAND", "DIRT", "GRASS", "GARDEN", "PARK", "STREET", "ROAD", "BRIDGE", "RIVER", "LAKE",
        "SEA", "WAVE", "BOAT", "SHIP", "PLANE", "TRAIN", "BUS", "TRUCK", "BICYCLE", "WALK",
        "RUN", "JUMP", "SWIM", "DANCE", "SING", "SONG", "VOICE", "NOISE", "PEACE", "CROWD",
        "EMPTY", "FULL", "BRIGHT", "DARK", "LIGHT", "SHADOW", "COLOR", "PAINT", "DRAW", "WRITE",
        "READ", "LISTEN", "SPEAK", "TALK", "ASK", "ANSWER", "QUESTION", "TRUE", "FALSE", "MAYBE",
        "YES", "NO", "PLEASE", "THANK", "SORRY", "HELLO", "GOODBYE", "WELCOME", "HOME", "FAMILY",
        "MOTHER", "FATHER", "SISTER", "BROTHER", "BABY", "CHILD", "ADULT", "GRANDMA", "GRANDPA", "AUNT",
        "UNCLE", "COUSIN", "WIFE", "HUSBAND", "WEDDING", "LOVER", "KISS", "HUG", "SMILE", "CRY",
        "LAUGH", "FEAR", "HOPE", "DREAM", "SLEEP", "WAKE", "REST", "PLAY", "GAME", "SPORT",
        "SOCCER", "BASKETBALL", "TENNIS", "BALL", "GOAL", "WIN", "LOSE", "TEAM", "FUN", "TOY",
        "DOLL", "CAR", "BLOCK", "PUZZLE", "PICTURE", "MOVIE", "SHOW", "MUSIC", "RADIO", "TV",
        "COMPUTER", "SCREEN", "KEY", "MOUSE", "CLICK", "INTERNET", "EMAIL", "MESSAGE", "CALL", "CHAT",
        "FOOD", "DRINK", "COFFEE", "TEA", "JUICE", "CAKE", "COOKIE", "CANDY", "ICE", "SUGAR",
        "SALT", "PEPPER", "OIL", "BUTTER", "SOUP", "SALAD", "PLATE", "BOWL", "CUP", "SPOON",
        "FORK", "KNIFE", "COOK", "EAT", "TASTE", "SMELL", "TOUCH", "FEEL", "SEE", "HEAR",
        "WATCH", "LOOK", "FIND", "LOSE", "SEARCH", "HIDE", "OPEN", "CLOSE", "START", "STOP",
        "BEGIN", "END", "NOW", "LATER", "SOON", "EARLY", "LATE", "TODAY", "TOMORROW", "YESTERDAY",
        "WEEK", "MONTH", "YEAR", "HOUR", "MINUTE", "SECOND", "SUMMER", "WINTER", "SPRING", "FALL",
        "WEATHER", "STORM", "THUNDER", "LIGHTNING", "FOG", "HEAT", "ICE", "FIRE", "SMOKE", "ASH",
        "WOOD", "METAL", "GLASS", "PLASTIC", "PAPER", "BOX", "BAG", "BOTTLE", "CAN", "JAR",
        "CLOTHES", "SHIRT", "PANTS", "DRESS", "SHOES", "SOCKS", "HAT", "COAT", "JACKET", "GLOVE",
        "SCARF", "BELT", "BAG", "WALLET", "KEY", "LOCK", "WALL", "FLOOR", "CEILING", "ROOF",
        "STAIR", "LADDER", "ELEVATOR", "BALCONY", "CURTAIN", "RUG", "SOFA", "COUCH", "PILLOW", "BLANKET",
        "SHEET", "TOWEL", "SOAP", "SHAMPOO", "BRUSH", "COMB", "MIRROR", "SINK", "BATH", "SHOWER",
        "TOILET", "TRASH", "CLEAN", "WASH", "DRY", "IRON", "FOLD", "CUT", "SEW", "NEEDLE",
        "THREAD", "BUTTON", "ZIPPER", "POCKET", "HOLE", "PATCH", "WEAR", "TAKE", "GIVE", "BUY",
        "SELL", "PRICE", "CHEAP", "EXPENSIVE", "STORE", "SHOP", "MARKET", "CASH", "CARD", "CHECK",
        "BILL", "COIN", "BANK", "SAVE", "SPEND", "RICH", "POOR", "JOB", "OFFICE", "BOSS",
        "WORKER", "MEET", "PLAN", "TRIP", "TRAVEL", "MAP", "CITY", "TOWN", "VILLAGE", "COUNTRY",
        "WORLD", "LAND", "WATER", "MOUNTAIN", "HILL", "VALLEY", "FOREST", "DESERT", "BEACH", "ISLAND",
        "FARM", "FIELD", "CROP", "PLANT", "GROW", "SEED", "HARVEST", "ANIMAL", "WILD", "PET",
        "CAGE", "FOOD", "HUNT", "FISH", "TRAP", "RIDE", "DRIVE", "FLY", "CRASH", "FIX",
        "BREAK", "BUILD", "HOUSE", "DOOR", "WINDOW", "WALL", "FLOOR", "ROOF", "TOOL", "HAMMER",
        "NAIL", "SCREW", "DRILL", "PAINT", "BRUSH", "LADDER", "WORK", "HELP", "SHARE", "LIFT",
        "CARRY", "PUSH", "PULL", "THROW", "CATCH", "KICK", "HIT", "ROLL", "SLIDE", "FALL",
        "CLIMB", "JUMP", "LAND", "TURN", "MOVE", "STAY", "LEAVE", "COME", "GO", "ARRIVE",
        "WAIT", "RUSH", "HURRY", "CALM", "PEACE", "FIGHT", "ARGUE", "AGREE", "DISAGREE", "CHOICE",
        "PICK", "CHOOSE", "DECIDE", "THINK", "KNOW", "LEARN", "TEACH", "STUDY", "TEST", "GRADE",
        "PASS", "FAIL", "TRY", "EFFORT", "WIN", "LOSE", "PRIZE", "GIFT", "SURPRISE", "PARTY",
        "CELEBRATE", "BIRTHDAY", "HOLIDAY", "CHRISTMAS", "HALLOWEEN", "THANKS", "NEW", "YEAR", "EASTER", "FLAG",
        "SIGN", "NAME", "NUMBER", "COUNT", "ADD", "SUBTRACT", "MULTIPLY", "DIVIDE", "TOTAL", "SHAPE",
        "CIRCLE", "SQUARE", "TRIANGLE", "LINE", "POINT", "ROUND", "FLAT", "HIGH", "LOW", "DEEP",
        "SHALLOW", "WIDE", "NARROW", "NEAR", "FAR", "LEFT", "RIGHT", "UP", "DOWN", "INSIDE",
        "OUTSIDE", "TOP", "BOTTOM", "MIDDLE", "SIDE", "FRONT", "BACK", "NEXT", "LAST", "FIRST"
    ],
    de: [
        "APFEL", "BALL", "KATZE", "HUND", "EI", "FISCH", "MÄDCHEN", "JUNGE", "HAUS", "AUTO",
        "WASSER", "MILCH", "BROT", "KÄSE", "FLEISCH", "OBST", "ORANGE", "BANANE", "TRAUBE", "BIRNE",
        "TISCH", "STUHL", "TÜR", "FENSTER", "ZIMMER", "BETT", "UHR", "TELEFON", "BUCH", "STIFT",
        "PAPIER", "SCHULE", "LEHRER", "SCHÜLER", "FREUND", "ARBEIT", "GELD", "ZEIT", "TAG", "NACHT",
        "MORGEN", "ABEND", "SONNE", "MOND", "STERN", "HIMMEL", "WOLKE", "REGEN", "SCHNEE", "WIND",
        "BAUM", "BLUME", "VOGEL", "PFERD", "KUH", "SCHAF", "ZIEGE", "SCHWEIN", "HUHN", "ENTE",
        "HAND", "FUß", "KOPF", "AUGE", "OHR", "NASE", "MUND", "HAARE", "ARM", "BEIN",
        "LIEBE", "GLÜCKLICH", "TRAURIG", "GUT", "SCHLECHT", "GROß", "KLEIN", "LANG", "KURZ", "SCHNELL",
        "LANGSAM", "SCHÖN", "HÄSSLICH", "WARM", "KALT", "HEIß", "KÜHL", "NASS", "TROCKEN", "WEICH",
        "HART", "LAUT", "LEISE", "SAUBER", "SCHMUTZIG", "NEU", "ALT", "ROT", "BLAU", "GRÜN",
        "GELB", "SCHWARZ", "WEISS", "GRAU", "LILA", "ROSA", "BRAUN", "GOLD", "SILBER", "STEIN",
        "SAND", "ERDE", "GRAS", "GARTEN", "PARK", "STRASSE", "WEG", "BRÜCKE", "FLUSS", "SEE",
        "MEER", "WELLE", "BOOT", "SCHIFF", "FLUGZEUG", "ZUG", "BUS", "LKW", "FAHRRAD", "GEHEN",
        "LAUFEN", "SPRINGEN", "SCHWIMMEN", "TANZEN", "SINGEN", "LIED", "STIMME", "LÄRM", "RUHE", "MENGE",
        "LEER", "VOLL", "HELL", "DUNKEL", "LICHT", "SCHATTEN", "FARBE", "MALEN", "ZEICHNEN", "SCHREIBEN",
        "LESEN", "HÖREN", "SPRECHEN", "REDEN", "FRAGEN", "ANTWORT", "FRAGE", "WAHR", "FALSCH", "VIELLEICHT",
        "JA", "NEIN", "BITTE", "DANKE", "ENTSCHULDIGUNG", "HALLO", "TSCHÜSS", "WILLKOMMEN", "ZUHAUSE", "FAMILIE",
        "MUTTER", "VATER", "SCHWESTER", "BRUDER", "BABY", "KIND", "ERWACHSENER", "OMA", "OPA", "TANTE",
        "ONKEL", "COUSIN", "FRAU", "MANN", "HOCHZEIT", "LIEBHABER", "KUSS", "UMARMUNG", "LÄCHELN", "WEINEN",
        "LACHEN", "ANGST", "HOFFNUNG", "TRAUM", "SCHLAF", "WACH", "RUHEN", "SPIELEN", "SPIEL", "SPORT",
        "FUSSBALL", "BASKETBALL", "TENNIS", "BALL", "TOR", "GEWINNEN", "VERLIEREN", "TEAM", "SPASS", "SPIELZEUG",
        "PUPPE", "AUTO", "BAUSTEIN", "PUZZLE", "BILD", "FILM", "SHOW", "MUSIK", "RADIO", "FERNSEHER",
        "COMPUTER", "BILDSCHIRM", "TASTE", "MAUS", "KLICK", "INTERNET", "EMAIL", "NACHRICHT", "ANRUF", "CHAT",
        "ESSEN", "TRINKEN", "KAFFEE", "TEE", "SAFT", "KUCHEN", "KEKS", "SÜSSIGKEIT", "EIS", "ZUCKER",
        "SALZ", "PFEFFER", "ÖL", "BUTTER", "SUPPE", "SALAT", "TELLER", "SCHÜSSEL", "TASSE", "LÖFFEL",
        "GABEL", "MESSER", "KOCHEN", "ESSEN", "SCHMECKEN", "RIECHEN", "BERÜHREN", "FÜHLEN", "SEHEN", "HÖREN",
        "SCHAUEN", "SUCHEN", "FINDEN", "VERLIEREN", "VERSTECKEN", "ÖFFNEN", "SCHLIESSEN", "STARTEN", "STOPPEN", "ANFANG",
        "ENDE", "JETZT", "SPÄTER", "BALD", "FRÜH", "SPÄT", "HEUTE", "MORGEN", "GESTERN", "WOCHE",
        "MONAT", "JAHR", "STUNDE", "MINUTE", "SEKUNDE", "SOMMER", "WINTER", "FRÜHLING", "HERBST", "WETTER",
        "STURM", "DONNER", "BLITZ", "NEBEL", "HITZE", "EIS", "FEUER", "RAUCH", "ASCHE", "HOLZ",
        "METALL", "GLAS", "PLASTIK", "PAPIER", "KARTON", "TASCHE", "FLASCHE", "DOSE", "GLAS", "KLEIDUNG",
        "HEMD", "HOSE", "KLEID", "SCHUHE", "SOCKEN", "HUT", "MANTEL", "JACKE", "HANDSCHUH", "SCHAL",
        "GÜRTEL", "TASCHE", "GELDBÖRSE", "SCHLÜSSEL", "SCHLOSS", "WAND", "BODEN", "DECKE", "DACH", "TREPPEN",
        "LEITER", "AUFZUG", "BALKON", "VORHANG", "TEPPICH", "SOFA", "COUCH", "KISSEN", "DECKE", "BETTWÄSCHE",
        "HANDTUCH", "SEIFE", "SHAMPOO", "BÜRSTE", "KAMM", "SPIEGEL", "WASCHBECKEN", "BAD", "DUSCHE", "TOILETTE",
        "MÜLL", "REINIGEN", "WASCHEN", "TROCKNEN", "BÜGELN", "FALTEN", "SCHNEIDEN", "NÄHEN", "NADEL", "FADEN",
        "KNOPF", "REISSVERSCHLUSS", "TASCHE", "LOCH", "FLICKEN", "TRAGEN", "NEHMEN", "GEBEN", "KAUFEN", "VERKAUFEN",
        "PREIS", "BILLIG", "TEUER", "LADEN", "GESCHÄFT", "MARKT", "BARGELD", "KARTE", "SCHECK", "RECHNUNG",
        "MÜNZE", "BANK", "SPAREN", "AUSGEBEN", "REICH", "ARM", "JOB", "BÜRO", "CHEF", "ARBEITER",
        "TREFFEN", "PLAN", "REISE", "FAHREN", "KARTE", "STADT", "DORF", "LAND", "WELT", "LAND",
        "WASSER", "BERG", "HÜGEL", "TAL", "WALD", "WÜSTE", "STRAND", "INSEL", "BAUERNHOF", "FELD",
        "PFLANZE", "WACHSEN", "SAMEN", "ERNTEN", "TIER", "WILD", "HAUSTIER", "KÄFIG", "FUTTER", "JAGEN",
        "ANGELN", "FALLE", "REITEN", "FAHREN", "FLIEGEN", "ABSTÜRZEN", "REPAREREN", "KAPUTT", "BAUEN", "HAUS",
        "TÜR", "FENSTER", "WAND", "BODEN", "DACH", "WERKZEUG", "HAMMER", "NAGEL", "SCHRAUBE", "BOHRER",
        "FARBE", "PINSEL", "LEITER", "ARBEIT", "HILFE", "TEILEN", "HEBEN", "TRAGEN", "SCHIEBEN", "ZIEHEN",
        "WERFEN", "FANGEN", "TREFFEN", "ROLLEN", "GLEITEN", "FALLEN", "KLETTERN", "SPRINGEN", "LANDEN", "DREHEN",
        "BEWEGEN", "BLEIBEN", "VERLASSEN", "KOMMEN", "GEHEN", "ANKOMMEN", "WARTEN", "EILEN", "RUHIG", "KÄMPFEN",
        "STREITEN", "EINIG", "UNEINS", "WAHL", "AUSWÄHLEN", "ENTSCHEIDEN", "DENKEN", "WISSEN", "LERNEN", "LEHREN",
        "STUDIEREN", "TEST", "NOTE", "BESTEHEN", "DURCHFALLEN", "VERSUCHEN", "ANSTRENGUNG", "GEWINNEN", "VERLIEREN", "PREIS",
        "GESCHENK", "ÜBERRASCHUNG", "PARTY", "FEIERN", "GEBURTSTAG", "URLAUB", "WEIHNACHTEN", "HALLOWEEN", "DANKSAGUNG", "NEUJAHR",
        "OSTERN", "FLAGGE", "ZEICHEN", "NAME", "NUMMER", "ZÄHLEN", "ADDEREN", "SUBTRAHIEREN", "MULTIPLIZIEREN", "TEILEN",
        "GESAMT", "FORM", "KREIS", "QUADRAT", "DREIECK", "LINIE", "PUNKT", "RUND", "FLACH", "HOCH",
        "NIEDRIG", "TIEF", "SEICHT", "BREIT", "ENG", "NAHE", "WEIT", "LINKS", "RECHTS", "OBEN",
        "UNTEN", "INNEN", "AUSSEN", "VORNE", "HINTEN", "NÄCHSTE", "LETZTE", "ERSTE"
    ],
    fr: [
        "POMME", "BALLE", "CHAT", "CHIEN", "OEUF", "POISSON", "FILLE", "GARCON", "MAISON", "VOITURE",
        "EAU", "LAIT", "PAIN", "FROMAGE", "VIANDE", "FRUIT", "ORANGE", "BANANE", "RAISIN", "POIRE",
        "TABLE", "CHAISE", "PORTE", "FENETRE", "CHAMBRE", "LIT", "HORLOGE", "TELEPHONE", "LIVRE", "STYLO",
        "PAPIER", "ECOLE", "PROFESSEUR", "ELEVE", "AMI", "TRAVAIL", "ARGENT", "TEMPS", "JOUR", "NUIT",
        "MATIN", "SOIR", "SOLEIL", "LUNE", "ETOILE", "CIEL", "NUAGE", "PLUIE", "NEIGE", "VENT",
        "ARBRE", "FLEUR", "OISEAU", "CHEVAL", "VACHE", "MOUTON", "CHEVRE", "COCHON", "POULE", "CANARD",
        "MAIN", "PIED", "TETE", "OEIL", "OREILLE", "NEZ", "BOUCHE", "CHEVEUX", "BRAS", "JAMBE",
        "AMOUR", "HEUREUX", "TRISTE", "BON", "MAUVAIS", "GRAND", "PETIT", "LONG", "COURT", "RAPIDE",
        "LENT", "JOLI", "LAID", "CHAUD", "FROID", "TIEDE", "FRAIS", "MOUILLE", "SEC", "DOUX",
        "DUR", "FORT", "CALME", "PROPRE", "SALE", "NEUF", "VIEUX", "ROUGE", "BLEU", "VERT",
        "JAUNE", "NOIR", "BLANC", "GRIS", "VIOLET", "ROSE", "MARRON", "OR", "ARGENT", "PIERRE",
        "SABLE", "TERRE", "HERBE", "JARDIN", "PARC", "RUE", "ROUTE", "PONT", "RIVIERE", "LAC",
        "MER", "VAGUE", "BATEAU", "NAVIRE", "AVION", "TRAIN", "BUS", "CAMION", "VELO", "MARCHER",
        "COURIR", "SAUTER", "NAGER", "DANSER", "CHANTER", "CHANSON", "VOIX", "BRUIT", "SILENCE", "FOULE",
        "VIDE", "PLEIN", "CLAIR", "SOMBRE", "LUMIERE", "OMBRE", "COULEUR", "PEINDRE", "DESSINER", "ECRIRE",
        "LIRE", "ECOUTER", "PARLER", "DISCUTER", "DEMANDER", "REPONDRE", "QUESTION", "VRAI", "FAUX", "PEUTETRE",
        "OUI", "NON", "SIL TE PLAIT", "MERCI", "PARDON", "BONJOUR", "AU REVOIR", "BIENVENUE", "MAISON", "FAMILLE",
        "MERE", "PERE", "SOEUR", "FRERE", "BEBE", "ENFANT", "ADULTE", "MAMIE", "PAPI", "TANTE",
        "ONCLE", "COUSIN", "FEMME", "MARI", "MARIAGE", "AMANT", "BAISER", "ETREINTE", "SOURIRE", "PLEURER",
        "RIRE", "PEUR", "ESPOIR", "REVE", "SOMMEIL", "REVEIL", "REPOS", "JOUER", "JEU", "SPORT",
        "FOOTBALL", "BASKET", "TENNIS", "BALLON", "BUT", "GAGNER", "PERDRE", "EQUIPE", "AMUSANT", "JOUET",
        "POUPEE", "VOITURE", "BRIQUE", "PUZZLE", "IMAGE", "FILM", "SPECTACLE", "MUSIQUE", "RADIO", "TELE",
        "ORDINATEUR", "ECRAN", "CLE", "SOURIS", "CLIC", "INTERNET", "EMAIL", "MESSAGE", "APPEL", "DISCUSSION",
        "NOURRITURE", "BOISSON", "CAFE", "THE", "JUS", "GATEAU", "BISCUIT", "BONBON", "GLACE", "SUCRE",
        "SEL", "POIVRE", "HUILE", "BEURRE", "SOUPE", "SALADE", "ASSIETTE", "BOL", "TASSE", "CUILLERE",
        "FOURCHETTE", "COUTEAU", "CUISINER", "MANGER", "GOUTER", "SENTIR", "TOUCHER", "RESSENTIR", "VOIR", "ENTENDRE",
        "REGARDER", "CHERCHER", "TROUVER", "PERDRE", "CACHER", "OUVRIR", "FERMER", "COMMENCER", "ARRETER", "DEBUT",
        "FIN", "MAINTENANT", "PLUS TARD", "BIENTOT", "TOT", "TARD", "AUJOURDHUI", "DEMAIN", "HIER", "SEMAINE",
        "MOIS", "ANNEE", "HEURE", "MINUTE", "SECONDE", "ETE", "HIVER", "PRINTEMPS", "AUTOMNE", "TEMPS",
        "TEMPETE", "TONNERRE", "ECLAIR", "BROUILLARD", "CHALEUR", "GLACE", "FEU", "FUMEE", "CENDRE", "BOIS",
        "METAL", "VERRE", "PLASTIQUE", "PAPIER", "BOITE", "SAC", "BOUTEILLE", "BOITE", "POT", "VETEMENTS",
        "CHEMISE", "PANTALON", "ROBE", "CHAUSSURES", "CHAUSSETTES", "CHAPEAU", "MANTEAU", "VESTE", "GANTS", "ECHARPE",
        "CEINTURE", "SAC", "PORTEFEUILLE", "CLE", "SERRURE", "MUR", "SOL", "PLAFOND", "TOIT", "ESCALIER",
        "ECHELLE", "ASCENSEUR", "BALCON", "RIDEAU", "TAPIS", "CANAPE", "FAUTEUIL", "OREILLER", "COUVERTURE", "DRAP",
        "SERVIETTE", "SAVON", "SHAMPOING", "BROSSE", "PEIGNE", "MIROIR", "LAVABO", "BAIN", "DOUCHE", "TOILETTES",
        "POUBELLE", "NETTOYER", "LAVER", "SECHER", "REPASSER", "PLIER", "COUPER", "COUDRE", "AIGUILLE", "FIL",
        "BOUTON", "FERMETURE", "POCHE", "TROU", "RAPIECER", "PORTER", "PRENDRE", "DONNER", "ACHETER", "VENDRE",
        "PRIX", "BON MARCHE", "CHER", "MAGASIN", "BOUTIQUE", "MARCHE", "ESPECES", "CARTE", "CHEQUE", "FACTURE",
        "PIECE", "BANQUE", "ECONOMISER", "DEPENSER", "RICHE", "PAUVRE", "EMPLOI", "BUREAU", "PATRON", "TRAVAILLEUR",
        "RENCONTRE", "PLAN", "VOYAGE", "CARTE", "VILLE", "VILLAGE", "PAYS", "MONDE", "TERRE", "EAU",
        "MONTAGNE", "COLLINE", "VALLEE", "FORET", "DESERT", "PLAGE", "ILE", "FERME", "CHAMP", "PLANTE",
        "POUSSER", "GRAINE", "RECOLTE", "ANIMAL", "SAUVAGE", "DOMESTIQUE", "CAGE", "NOURRITURE", "CHASSER", "PECHER",
        "PIEGE", "MONTER", "CONDUIRE", "VOLER", "CRASH", "REPARER", "CASSER", "CONSTRUIRE", "MAISON", "PORTE",
        "FENETRE", "MUR", "SOL", "TOIT", "OUTIL", "MARTEAU", "CLOU", "VIS", "PERCEUSE", "PEINTURE",
        "PINCEAU", "ECHELLE", "TRAVAIL", "AIDE", "PARTAGER", "SOULEVER", "PORTER", "POUSSER", "TIRER", "JETER",
        "ATTRAPER", "FRAPPER", "ROULER", "GLISSER", "TOMBER", "GRIMPER", "SAUTER", "ATTERRIR", "TOURNER", "BOUGER",
        "RESTER", "PARTIR", "VENIR", "ALLER", "ARRIVER", "ATTENDRE", "SE DEPECHER", "CALME", "SE BATTRE", "DISPUTER",
        "DACCORD", "PAS DACCORD", "CHOIX", "CHOISIR", "DECIDER", "PENSER", "SAVOIR", "APPRENDRE", "ENSEIGNER", "ETUDIER",
        "TEST", "NOTE", "REUSSIR", "ECHOUER", "ESSAYER", "EFFORT", "GAGNER", "PERDRE", "PRIX", "CADEAU",
        "SURPRISE", "FETE", "CELEBRER", "ANNIVERSAIRE", "VACANCES", "NOEL", "HALLOWEEN", "MERCI", "NOUVEL AN", "PAQUES",
        "DRAPEAU", "SIGNE", "NOM", "NUMERO", "COMPTER", "AJOUTER", "SOUSTRAIRE", "MULTIPLIER", "DIVISER", "TOTAL",
        "FORME", "CERCLE", "CARRE", "TRIANGLE", "LIGNE", "POINT", "ROND", "PLAT", "HAUT", "BAS",
        "PROFOND", "PEU PROFOND", "LARGE", "ETROIT", "PRES", "LOIN", "GAUCHE", "DROITE", "EN HAUT", "EN BAS",
        "DEDANS", "DEHORS", "DESSUS", "DESSOUS", "MILIEU", "COTE", "DEVANT", "DERRIERE", "SUIVANT", "DERNIER"
    ],
    es: [
        "MANZANA", "PELOTA", "GATO", "PERRO", "HUEVO", "PEZ", "NINA", "NINO", "CASA", "COCHE",
        "AGUA", "LECHE", "PAN", "QUESO", "CARNE", "FRUTA", "NARANJA", "PLATANO", "UVA", "PERA",
        "MESA", "SILLA", "PUERTA", "VENTANA", "HABITACION", "CAMA", "RELOJ", "TELEFONO", "LIBRO", "BOLIGRAFO",
        "PAPEL", "ESCUELA", "PROFESOR", "ALUMNO", "AMIGO", "TRABAJO", "DINERO", "TIEMPO", "DIA", "NOCHE",
        "MANANA", "TARDE", "SOL", "LUNA", "ESTRELLA", "CIELO", "NUBE", "LLUVIA", "NIEVE", "VIENTO",
        "ARBOL", "FLOR", "PAJARO", "CABALLO", "VACA", "OVEJA", "CABRA", "CERDO", "GALLINA", "PATO",
        "MANO", "PIE", "CABEZA", "OJO", "OREJA", "NARIZ", "BOCA", "PELO", "BRAZO", "PIERNA",
        "AMOR", "FELIZ", "TRISTE", "BUENO", "MALO", "GRANDE", "PEQUENO", "LARGO", "CORTO", "RAPIDO",
        "LENTO", "BONITO", "FEO", "CALIENTE", "FRIO", "TIBIO", "FRESCO", "MOJADO", "SECO", "SUAVE",
        "DURO", "FUERTE", "CALMADO", "LIMPIO", "SUCIO", "NUEVO", "VIEJO", "ROJO", "AZUL", "VERDE",
        "AMARILLO", "NEGRO", "BLANCO", "GRIS", "MORADO", "ROSA", "MARRON", "ORO", "PLATA", "PIEDRA",
        "ARENA", "TIERRA", "HIERBA", "JARDIN", "PARQUE", "CALLE", "CAMINO", "PUENTE", "RIO", "LAGO",
        "MAR", "OLA", "BARCO", "NAVIO", "AVION", "TREN", "AUTOBUS", "CAMION", "BICICLETA", "CAMINAR",
        "CORRER", "SALTAR", "NADAR", "BAILAR", "CANTAR", "CANCION", "VOZ", "RUIDO", "SILENCIO", "MULTITUD",
        "VACIO", "LLENO", "CLARO", "OSCURO", "LUZ", "SOMBRA", "COLOR", "PINTAR", "DIBUJAR", "ESCRIBIR",
        "LEER", "ESCUCHAR", "HABLAR", "CHARLAR", "PREGUNTAR", "RESPONDER", "PREGUNTA", "VERDAD", "FALSO", "QUIZAS",
        "SI", "NO", "POR FAVOR", "GRACIAS", "PERDON", "HOLA", "ADIOS", "BIENVENIDO", "CASA", "FAMILIA",
        "MADRE", "PADRE", "HERMANA", "HERMANO", "BEBE", "NINO", "ADULTO", "ABUELA", "ABUELO", "TIA",
        "TIO", "PRIMO", "ESPOSA", "MARIDO", "BODA", "AMANTE", "BESO", "ABRAZO", "SONRISA", "LLORAR",
        "REIR", "MIEDO", "ESPERANZA", "SUENO", "DORMIR", "DESPERTAR", "DESCANSO", "JUGAR", "JUEGO", "DEPORTE",
        "FUTBOL", "BALONCESTO", "TENIS", "BALON", "GOL", "GANAR", "PERDER", "EQUIPO", "DIVERTIDO", "JUGUETE",
        "MUNECA", "COCHE", "LADRILLO", "ROMPECABEZAS", "IMAGEN", "PELICULA", "ESPECTACULO", "MUSICA", "RADIO", "TELE",
        "ORDENADOR", "PANTALLA", "LLAVE", "RATON", "CLIC", "INTERNET", "CORREO", "MENSAJE", "LLAMADA", "CHARLA",
        "COMIDA", "BEBIDA", "CAFE", "TE", "JUGO", "PASTEL", "GALLETA", "CARAMELO", "HELADO", "AZUCAR",
        "SAL", "PIMIENTA", "ACEITE", "MANTEQUILLA", "SOPA", "ENSALADA", "PLATO", "TAZA", "VASO", "CUCHARA",
        "TENEDOR", "CUCHILLO", "COCINAR", "COMER", "PROBAR", "OLER", "TOCAR", "SENTIR", "VER", "OIR",
        "MIRAR", "BUSCAR", "ENCONTRAR", "PERDER", "ESCONDER", "ABRIR", "CERRAR", "EMPEZAR", "PARAR", "COMIENZO",
        "FIN", "AHORA", "MAS TARDE", "PRONTO", "TEMPRANO", "TARDE", "HOY", "MANANA", "AYER", "SEMANA",
        "MES", "ANO", "HORA", "MINUTO", "SEGUNDO", "VERANO", "INVIERNO", "PRIMAVERA", "OTONO", "TIEMPO",
        "TORMENTA", "TRUENO", "RAYO", "NIEBLA", "CALOR", "HIELO", "FUEGO", "HUMO", "CENIZA", "MADERA",
        "METAL", "VIDRIO", "PLASTICO", "PAPEL", "CAJA", "BOLSA", "BOTELLA", "LATA", "TARRO", "ROPA",
        "CAMISA", "PANTALON", "VESTIDO", "ZAPATOS", "CALCETINES", "SOMBRERO", "ABRIGO", "CHAQUETA", "GUANTES", "BUFANDA",
        "CINTURON", "BOLSA", "CARTERA", "LLAVE", "CERRADURA", "PARED", "SUELO", "TECHO", "TEJADO", "ESCALERA",
        "ESCALERA", "ASCENSOR", "BALCON", "CORTINA", "ALFOMBRA", "SOFA", "SILLON", "ALMOHADA", "MANTA", "SABANA",
        "TOALLA", "JABON", "CHAMPU", "CEPILLO", "PEINE", "ESPEJO", "LAVABO", "BANO", "DUCHA", "INODORO",
        "BASURA", "LIMPIAR", "LAVAR", "SECAR", "PLANCHAR", "DOBLAR", "CORTAR", "COSER", "AGUJA", "HILO",
        "BOTON", "CREMALLERA", "BOLSILLO", "AGUJERO", "REMENDAR", "LLEVAR", "TOMAR", "DAR", "COMPRAR", "VENDER",
        "PRECIO", "BARATO", "CARO", "TIENDA", "BOUTIQUE", "MERCADO", "EFECTIVO", "TARJETA", "CHEQUE", "FACTURA",
        "MONEDA", "BANCO", "AHORRAR", "GASTAR", "RICO", "POBRE", "EMPLEO", "OFICINA", "JEFE", "TRABAJADOR",
        "ENCUENTRO", "PLAN", "VIAJE", "MAPA", "CIUDAD", "PUEBLO", "PAIS", "MUNDO", "TIERRA", "AGUA",
        "MONTANA", "COLINA", "VALLE", "BOSQUE", "DESIERTO", "PLAYA", "ISLA", "GRANJA", "CAMPO", "PLANTA",
        "CRECER", "SEMILLA", "COSECHA", "ANIMAL", "SALVAJE", "DOMESTICO", "JAULA", "COMIDA", "CAZAR", "PESCAR",
        "TRAMPA", "MONTAR", "CONDUCIR", "VOLAR", "CHOQUE", "REPARAR", "ROMPER", "CONSTRUIR", "CASA", "PUERTA",
        "VENTANA", "PARED", "SUELO", "TEJADO", "HERRAMIENTA", "MARTILLO", "CLAVO", "TORNILLO", "TALADRO", "PINTURA",
        "BROCHA", "ESCALERA", "TRABAJO", "AYUDA", "COMPARTIR", "LEVANTAR", "LLEVAR", "EMPUJAR", "TIRAR", "LANZAR",
        "ATRAPAR", "GOLPEAR", "RODAR", "DESLIZAR", "CAER", "ESCALAR", "SALTAR", "ATERRIZAR", "GIRAR", "MOVER",
        "QUEDAR", "SALIR", "VENIR", "IR", "LLEGAR", "ESPERAR", "APURARSE", "CALMA", "PELEAR", "DISCUTIR",
        "DE ACUERDO", "NO DE ACUERDO", "ELECCION", "ELEGIR", "DECIDIR", "PENSAR", "SABER", "APRENDER", "ENSENAR", "ESTUDIAR",
        "EXAMEN", "NOTA", "APROBAR", "SUSPENDER", "INTENTAR", "ESFUERZO", "GANAR", "PERDER", "PREMIO", "REGALO",
        "SORPRESA", "FIESTA", "CELEBRAR", "CUMPLEANOS", "VACACIONES", "NAVIDAD", "HALLOWEEN", "GRACIAS", "ANO NUEVO", "PASCUA",
        "BANDERA", "SENAL", "NOMBRE", "NUMERO", "CONTAR", "SUMAR", "RESTAR", "MULTIPLICAR", "DIVIDIR", "TOTAL",
        "FORMA", "CIRCULO", "CUADRADO", "TRIANGULO", "LINEA", "PUNTO", "REDONDO", "PLANO", "ALTO", "BAJO",
        "PROFUNDO", "POCO PROFUNDO", "ANCHO", "ESTRECHO", "CERCA", "LEJOS", "IZQUIERDA", "DERECHA", "ARRIBA", "ABAJO",
        "DENTRO", "FUERA", "ENCIMA", "DEBAJO", "MEDIO", "LADO", "DELANTE", "DETRAS", "SIGUIENTE", "ULTIMO"
    ],
    ru: [
        "ЯБЛОКО", "МЯЧ", "КОТ", "СОБАКА", "ЯЙЦО", "РЫБА", "ДЕВОЧКА", "МАЛЬЧИК", "ДОМ", "МАШИНА",
        "ВОДА", "МОЛОКО", "ХЛЕБ", "СЫР", "МЯСО", "ФРУКТ", "АПЕЛЬСИН", "БАНАН", "ВИНОГРАД", "ГРУША",
        "СТОЛ", "СТУЛ", "ДВЕРЬ", "ОКНО", "КОМНАТА", "КРОВАТЬ", "ЧАСЫ", "ТЕЛЕФОН", "КНИГА", "РУЧКА",
        "БУМАГА", "ШКОЛА", "УЧИТЕЛЬ", "УЧЕНИК", "ДРУГ", "РАБОТА", "ДЕНЬГИ", "ВРЕМЯ", "ДЕНЬ", "НОЧЬ",
        "УТРО", "ВЕЧЕР", "СОЛНЦЕ", "ЛУНА", "ЗВЕЗДА", "НЕБО", "ОБЛАКО", "ДОЖДЬ", "СНЕГ", "ВЕТЕР",
        "ДЕРЕВО", "ЦВЕТОК", "ПТИЦА", "ЛОШАДЬ", "КОРОВА", "ОВЦА", "КОЗА", "СВИНЬЯ", "КУРИЦА", "УТКА",
        "РУКА", "НОГА", "ГОЛОВА", "ГЛАЗ", "УХО", "НОС", "РОТ", "ВОЛОСЫ", "РУКА", "НОГА",
        "ЛЮБОВЬ", "СЧАСТЛИВЫЙ", "ГРУСТНЫЙ", "ХОРОШИЙ", "ПЛОХОЙ", "БОЛЬШОЙ", "МАЛЕНЬКИЙ", "ДЛИННЫЙ", "КОРОТКИЙ", "БЫСТРЫЙ",
        "МЕДЛЕННЫЙ", "КРАСИВЫЙ", "НЕКРАСИВЫЙ", "ТЕПЛЫЙ", "ХОЛОДНЫЙ", "ГОРЯЧИЙ", "СВЕЖИЙ", "МОКРЫЙ", "СУХОЙ", "МЯГКИЙ",
        "ТВЕРДЫЙ", "ГРОМКИЙ", "ТИХИЙ", "ЧИСТЫЙ", "ГРЯЗНЫЙ", "НОВЫЙ", "СТАРЫЙ", "КРАСНЫЙ", "СИНИЙ", "ЗЕЛЕНЫЙ",
        "ЖЕЛТЫЙ", "ЧЕРНЫЙ", "БЕЛЫЙ", "СЕРЫЙ", "ФИОЛЕТОВЫЙ", "РОЗОВЫЙ", "КОРИЧНЕВЫЙ", "ЗОЛОТОЙ", "СЕРЕБРЯНЫЙ", "КАМЕНЬ",
        "ПЕСОК", "ЗЕМЛЯ", "ТРАВА", "САД", "ПАРК", "УЛИЦА", "ДОРОГА", "МОСТ", "РЕКА", "ОЗЕРО",
        "МОРЕ", "ВОЛНА", "ЛОДКА", "КОРАБЛЬ", "САМОЛЁТ", "ПОЕЗД", "АВТОБУС", "ГРУЗОВИК", "ВЕЛОСИПЕД", "ИДТИ",
        "БЕЖАТЬ", "ПРЫГАТЬ", "ПЛАВАТЬ", "ТАНЦЕВАТЬ", "ПЕТЬ", "ПЕСНЯ", "ГОЛОС", "ШУМ", "ТИШИНА", "ТОЛПА",
        "ПУСТОЙ", "ПОЛНЫЙ", "СВЕТЛЫЙ", "ТЕМНЫЙ", "СВЕТ", "ТЕНИ", "ЦВЕТ", "КРАСИТЬ", "РИСОВАТЬ", "ПИСАТЬ",
        "ЧИТАТЬ", "СЛУШАТЬ", "ГОВОРИТЬ", "РАЗГОВАРИВАТЬ", "СПРАШИВАТЬ", "ОТВЕЧАТЬ", "ВОПРОС", "ПРАВДА", "ЛОЖЬ", "МОЖЕТ",
        "ДА", "НЕТ", "ПОЖАЛУЙСТА", "СПАСИБО", "ИЗВИНИ", "ПРИВЕТ", "ДО СВИДАНИЯ", "ДОБРО ПОЖАЛОВАТЬ", "ДОМ", "СЕМЬЯ",
        "МАМА", "ПАПА", "СЕСТРА", "БРАТ", "МАЛЫШ", "РЕБЕНОК", "ВЗРОСЛЫЙ", "БАБУШКА", "ДЕДУШКА", "ТЁТЯ",
        "ДЯДЯ", "КУЗЕН", "ЖЕНА", "МУЖ", "СВАДЬБА", "ЛЮБОВНИК", "ПОЦЕЛУЙ", "ОБЪЯТИЯ", "УЛЫБКА", "ПЛАКАТЬ",
        "СМЕЯТЬСЯ", "СТРАХ", "НАДЕЖДА", "СОН", "СПАТЬ", "ПРОСЫПАТЬСЯ", "ОТДЫХ", "ИГРАТЬ", "ИГРА", "СПОРТ",
        "ФУТБОЛ", "БАСКЕТБОЛ", "ТЕНИС", "МЯЧ", "ГОЛ", "ВЫИГРАТЬ", "ПРОИГРАТЬ", "КОМАНДА", "ВЕСЕЛЫЙ", "ИГРУШКА",
        "КУКЛА", "МАШИНА", "КУБИК", "ПУЗЗЛ", "КАРТИНКА", "ФИЛЬМ", "ШОУ", "МУЗЫКА", "РАДИО", "ТЕЛЕВИЗОР",
        "КОМПЬЮТЕР", "ЭКРАН", "КЛЮЧ", "МЫШЬ", "КЛИК", "ИНТЕРНЕТ", "ПОЧТА", "СООБЩЕНИЕ", "ЗВОНОК", "ЧАТ",
        "ЕДА", "НАПИТОК", "КОФЕ", "ЧАЙ", "СОК", "ТОРТ", "ПЕЧЕНЬЕ", "КОНФЕТА", "МОРОЖЕНОЕ", "САХАР",
        "СОЛЬ", "ПЕРЕЦ", "МАСЛО", "СЛИВОЧНОЕ МАСЛО", "СУП", "САЛАТ", "ТАРЕЛКА", "ЧАШКА", "СТАКАН", "ЛОЖКА",
        "ВИЛКА", "НОЖ", "ГОТОВИТЬ", "ЕСТЬ", "ПРОБОВАТЬ", "НЮХАТЬ", "ТРОГАТЬ", "ЧУВСТВОВАТЬ", "ВИДЕТЬ", "СЛЫШАТЬ",
        "СМОТРЕТЬ", "ИСКАТЬ", "НАХОДИТЬ", "ТЕРЯТЬ", "ПРЯТАТЬ", "ОТКРЫВАТЬ", "ЗАКРЫВАТЬ", "НАЧИНАТЬ", "ОСТАНАВЛИВАТЬ", "НАЧАЛО",
        "КОНЕЦ", "СЕЙЧАС", "ПОЗЖЕ", "СКОРО", "РАНО", "ПОЗДНО", "СЕГОДНЯ", "ЗАВТРА", "ВЧЕРА", "НЕДЕЛЯ",
        "МЕСЯЦ", "ГОД", "ЧАС", "МИНУТА", "СЕКУНДА", "ЛЕТО", "ЗИМА", "ВЕСНА", "ОСЕНЬ", "ПОГОДА",
        "БУРЯ", "ГРОМ", "МОЛНИЯ", "ТУМАН", "ЖАРА", "ЛЁД", "ОГОНЬ", "ДЫМ", "ПЕПЕЛ", "ДЕРЕВО",
        "МЕТАЛЛ", "СТЕКЛО", "ПЛАСТИК", "БУМАГА", "КОРОБКА", "СУМКА", "БУТЫЛКА", "БАНКА", "БАНКА", "ОДЕЖДА",
        "РУБАШКА", "БРЮКИ", "ПЛАТЬЕ", "ТУФЛИ", "НОСКИ", "ШЛЯПА", "ПАЛЬТО", "КУРТКА", "ПЕРЧАТКИ", "ШАРФ",
        "РЕМЕНЬ", "СУМКА", "КОШЕЛЁК", "КЛЮЧ", "ЗАМОК", "СТЕНА", "ПОЛ", "ПОТОЛОК", "КРЫША", "ЛЕСТНИЦА",
        "ЛЕСТНИЦА", "ЛИФТ", "БАЛКОН", "ШТОРА", "КОВЁР", "ДИВАН", "КРЕСЛО", "ПОДУШКА", "ОДЕЯЛО", "ПРОСТЫНЯ",
        "ПОЛОТЕНЦЕ", "МЫЛО", "ШАМПУНЬ", "ЩЁТКА", "РАСЧЁСКА", "ЗЕРКАЛО", "РАКОВИНА", "ВАННА", "ДУШ", "ТУАЛЕТ",
        "МУСОР", "ЧИСТИТЬ", "МЫТЬ", "СУШИТЬ", "ГЛАДИТЬ", "СКЛАДЫВАТЬ", "РЕЗАТЬ", "ШИТЬ", "ИГЛА", "НИТКА",
        "ПУГОВИЦА", "МОЛНИЯ", "КАРМАН", "ДЫРА", "ЧИНИТЬ", "НОСИТЬ", "БРАТЬ", "ДАВАТЬ", "ПОКУПАТЬ", "ПРОДАВАТЬ",
        "ЦЕНА", "ДЕШЁВЫЙ", "ДОРОГОЙ", "МАГАЗИН", "БУТИК", "РЫНОК", "НАЛИЧНЫЕ", "КАРТА", "ЧЕК", "СЧЁТ",
        "МОНЕТА", "БАНК", "КОПИТЬ", "ТРАТИТЬ", "БОГАТЫЙ", "БЕДНЫЙ", "РАБОТА", "ОФИС", "НАЧАЛЬНИК", "РАБОТНИК",
        "ВСТРЕЧА", "ПЛАН", "ПУТЕШЕСТВИЕ", "КАРТА", "ГОРОД", "ДЕРЕВНЯ", "СТРАНА", "МИР", "ЗЕМЛЯ", "ВОДА",
        "ГОРА", "ХОЛМ", "ДОЛИНА", "ЛЕС", "ПУСТЫНЯ", "ПЛЯЖ", "ОСТРОВ", "ФЕРМА", "ПОЛЕ", "РАСТЕНИЕ",
        "РАСТИ", "СЕМЯ", "УРОЖАЙ", "ЖИВОТНОЕ", "ДИКИЙ", "ДОМАШНИЙ", "КЛЕТКА", "ЕДА", "ОХОТИТЬСЯ", "ЛОВИТЬ РЫБУ",
        "ЛОВУШКА", "ЕХАТЬ", "ВОДИТЬ", "ЛЕТАТЬ", "АВАРИЯ", "ЧИНИТЬ", "ЛОМАТЬ", "СТРОИТЬ", "ДОМ", "ДВЕРЬ",
        "ОКНО", "СТЕНА", "ПОЛ", "КРЫША", "ИНСТРУМЕНТ", "МОЛОТОК", "ГВОЗДЬ", "ВИНТ", "ДРЕЛЬ", "КРАСКА",
        "КИСТЬ", "ЛЕСТНИЦА", "РАБОТА", "ПОМОЩЬ", "ДЕЛИТЬСЯ", "ПОДНИМАТЬ", "НОСИТЬ", "ТОЛКАТЬ", "ТЯНУТЬ", "БРОСАТЬ",
        "ЛОВИТЬ", "БИТЬ", "КАТИТЬ", "СКОЛЬЗИТЬ", "ПАДАТЬ", "ЛАЗИТЬ", "ПРЫГАТЬ", "ПРИЗЕМЛЯТЬСЯ", "ПОВОРАЧИВАТЬ", "ДВИГАТЬ",
        "ОСТАВАТЬСЯ", "УХОДИТЬ", "ПРИХОДИТЬ", "ИДТИ", "ПРИЕЗЖАТЬ", "ЖДАТЬ", "ТОРОПИТЬСЯ", "СПОКОЙНЫЙ", "ДРАТЬСЯ", "ССОРИТЬСЯ",
        "СОГЛАСЕН", "НЕ СОГЛАСЕН", "ВЫБОР", "ВЫБИРАТЬ", "РЕШАТЬ", "ДУМАТЬ", "ЗНАТЬ", "УЧИТЬСЯ", "УЧИТЬ", "ИЗУЧАТЬ",
        "ТЕСТ", "ОЦЕНКА", "СДАТЬ", "ПРОВАЛИТЬ", "ПЫТАТЬСЯ", "УСИЛИЕ", "ВЫИГРАТЬ", "ПРОИГРАТЬ", "ПРИЗ", "ПОДАРОК",
        "СЮРПРИЗ", "ПРАЗДНИК", "ПРАЗДНОВАТЬ", "ДЕНЬ РОЖДЕНИЯ", "КАНИКУЛЫ", "РОЖДЕСТВО", "ХЭЛЛОУИН", "СПАСИБО", "НОВЫЙ ГОД", "ПАСХА",
        "ФЛАГ", "ЗНАК", "ИМЯ", "ЧИСЛО", "СЧИТАТЬ", "СКЛАДЫВАТЬ", "ВЫЧИТАТЬ", "УМНОЖАТЬ", "ДЕЛИТЬ", "СУММА",
        "ФОРМА", "КРУГ", "КВАДРАТ", "ТРЕУГОЛЬНИК", "ЛИНИЯ", "ТОЧКА", "КРУГЛЫЙ", "ПЛОСКИЙ", "ВЫСОКИЙ", "НИЗКИЙ",
        "ГЛУБОКИЙ", "МЕЛКИЙ", "ШИРОКИЙ", "УЗКИЙ", "БЛИЗКО", "ДАЛЕКО", "ЛЕВЫЙ", "ПРАВЫЙ", "ВВЕРХ", "ВНИЗ",
        "ВНУТРИ", "СНАРУЖИ", "СВЕРХУ", "СНИЗУ", "СЕРЕДИНА", "СТОРОНА", "СПЕРЕДИ", "СЗАДИ", "СЛЕДУЮЩИЙ", "ПОСЛЕДНИЙ"
    ]
};

export { words };
